### ISSUE TITLE
Gateway error

### ISSUE THREAD

**Issue by closier** [DIRACGrid/DIRAC#1458]
I have installe LHCBDirac based on Dirac v6r8p11 and I get this error in Framework/Gateway:
==> Framework_Gateway/log/current <==
Traceback (most recent call last):
  File "/opt/dirac/pro/DIRAC/Core/scripts/dirac-service.py", line 39, in <module>
    result = serverToLaunch.initialize( positionalArgs )
  File "/opt/dirac/pro/DIRAC/Core/DISET/ServiceReactor.py", line 42, in initialize
    self.**services[ GatewayService.GATEWAY_NAME ] = GatewayService()
  File "/opt/dirac/pro/DIRAC/Core/DISET/private/GatewayService.py", line 30, in __init**
    Service.**init**( self, GatewayService.GATEWAY_NAME )
  File "/opt/dirac/pro/DIRAC/Core/DISET/private/Service.py", line 32, in **init**
    self._name = serviceData[ 'loadName' ]
TypeError: string indices must be integers, not str

**Comment by fstagni** [comment]
Closing as no updates.
