### ISSUE TITLE
DIPS as third party

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#2413]
Hi,

there were places were it was hard coded that dips could be used as a third party copy protocol. What it actually does is download locally, and then upload. The problem is that it doesn't work :-) 
```
Traceback (most recent call last):
  File "/home/cern/dirac/DIRAC/Interfaces/scripts/dirac-dms-replicate-lfn.py", line 50, in <module>
    result = dirac.replicateFile( lfn, seName, sourceSE, localCache, printOutput = True )
  File "/home/cern/dirac/DIRAC/Interfaces/API/Dirac.py", line 1364, in replicateFile
    result = dm.replicateAndRegister( lfn, destinationSE, sourceSE, '', localCache )
  File "/home/cern/dirac/DIRAC/DataManagementSystem/Client/DataLoggingDecorator.py", line 123, in __call__
    result = self.func( *args, **kwargs )
  File "/home/cern/dirac/DIRAC/DataManagementSystem/Client/DataManager.py", line 558, in replicateAndRegister
    res = self.__replicate( lfn, destSE, sourceSE, destPath, localCache )
  File "/home/cern/dirac/DIRAC/DataManagementSystem/Client/DataManager.py", line 838, in __replicate
    res = returnSingleResult( destStorageElement.replicateFile( {destPath:sourceURL}, sourceSize = catalogSize ) )
  File "/home/cern/dirac/DIRAC/DataManagementSystem/Client/DataLoggingDecorator.py", line 123, in __call__
    result = self.func( *args, **kwargs )
  File "/home/cern/dirac/DIRAC/Resources/Storage/StorageElement.py", line 742, in __executeMethod
    res = fcn( urlsToUse, *args, **kwargs )
  File "/home/cern/dirac/DIRAC/Resources/Storage/DIPStorage.py", line 94, in putFile
    res = self.__putFile( src_file, dest_url )
  File "/home/cern/dirac/DIRAC/Resources/Storage/DIPStorage.py", line 111, in __putFile
    transferClient = TransferClient( srcSEURL )
  File "/home/cern/dirac/DIRAC/Core/DISET/private/BaseClient.py", line 57, in __init__
    result = initFunc()
  File "/home/cern/dirac/DIRAC/Core/DISET/private/BaseClient.py", line 101, in __discoverURL
    retVal = Network.splitURL( self.serviceURL )
  File "/home/cern/dirac/DIRAC/Core/Utilities/Network.py", line 90, in splitURL
    while path[0] == '/':
IndexError: string index out of range
```

The problem is in the DIPStorage class, line 110, when constructing the srcSEURL. We don't append the equivalent of the base path, that is the name of the service. We construct something like "dips://myhost.something.com:1234", while it should be "dips://myhost.something.com:1234/DataManagemnt/StorageElementService" or something similar. The difficulty here is that you don't have the information of the source SE, you only get a source URL, out of which it is difficult (sometimes even impossible) to find this information. 
Anyway, with the current protocol negotiation we have in v6r13, it *should* be enough to remove dips from the list of third party protocol

**Comment by andresailer** [comment]
@fstagni: This issue looks like it is related to my log storage element writing to a different path in v6r14
I have the DIP SEs defined with something in the AccessProtocol.1/Path which used to be ignored. And now this Path is prepended to the local storage path. Leaving the "Path" empty (or just "/") causes the error as posted above.
I'll try removing "dips" from the ThirdPartyProtocol list and see what happens.

**Comment by chaen** [comment]
@fstagni why did you apply the "waiting for release" tag ? as far as I know, this is not fixed

**Comment by fstagni** [comment]
Ah I thought that https://github.com/andresailer/DIRAC/commit/40111f195c96ec21d36356fc4e1c3a3cb8e15825 + https://github.com/DIRACGrid/DIRAC/issues/2779 were fixing this issue. But I don't see the @andresailer  commit merged... why not?

CC @CinziaLu

**Comment by andresailer** [comment]
Made a pull request with my fix. At least the crash should disappear.
Though my problem was fixed by @atsareg

**Comment by fstagni** [comment]
Can this be closed then?

**Comment by chaen** [comment]
I **think** this PR https://github.com/DIRACGrid/DIRAC/pull/2979 is meant to fix it but not sure

**Comment by atsareg** [comment]
Yes, PR #2979 should fix it. This is not making the DIP storage to make a true third party transfer but at least it behaves like that.

**Comment by atsareg** [comment]
Fixed in v6r14p34, v6r15p3
