### ISSUE TITLE
Monitoring should never make an operation fail

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#2416]
Trying to do a data management operation, some accounting information were supposed to be send. Since it couldn't work, it tried to setup a Request to send the information. And as there was no RequestManagement system defined in the CS, the whole operation crashed with an exception

This is conceptually wrong. Monitoring should be on the best effort basis, and by no mean prevent the operation to happen

dirac-dms-add-file[OoYM]  ERROR: CS option RequestManagement/ReqManager URL is not set! 
Traceback (most recent call last):
  File "/home/cern/dirac/DIRAC/DataManagementSystem/scripts/dirac-dms-add-file.py", line 83, in <module>
    res = dm.putAndRegister( lfn['lfn'], lfn['localfile'], lfn['SE'], lfn['guid'] )
  File "/home/cern/dirac/DIRAC/DataManagementSystem/Client/DataLoggingDecorator.py", line 123, in **call**
    result = self.func( _args, *_kwargs )
  File "/home/cern/dirac/DIRAC/DataManagementSystem/Client/DataManager.py", line 501, in putAndRegister
    gDataStoreClient.commit()
  File "/home/cern/dirac/DIRAC/Core/Utilities/ThreadSafe.py", line 23, in lockedFunc
    return funcToCall(_args, *_kwargs)
  File "/home/cern/dirac/DIRAC/AccountingSystem/Client/DataStoreClient.py", line 87, in commit
    result = _sendToFailover( retVal[ 'rpcStub' ] )
  File "/home/cern/dirac/DIRAC/AccountingSystem/Client/DataStoreClient.py", line 125, in _sendToFailover
    return ReqClient().putRequest( request )
  File "/home/cern/dirac/DIRAC/RequestManagementSystem/Client/ReqClient.py", line 40, in __init__
    self.setServer( "RequestManagement/ReqManager" )
  File "/home/cern/dirac/DIRAC/RequestManagementSystem/Client/ReqClient.py", line 46, in setServer
    self.requestManager()
  File "/home/cern/dirac/DIRAC/RequestManagementSystem/Client/ReqClient.py", line 54, in requestManager
    raise RuntimeError( "CS option %s URL is not set!" % self.serverURL )
RuntimeError: CS option RequestManagement/ReqManager URL is not set!

**Comment by chaen** [comment]
This was fixed, so I close
