### ISSUE TITLE
Verify dirac-rss-dt-query-cache

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#2846]
Seems it's buggy:

``
[fstagni@lxplus0080 ~/DEVClient]$ dirac-rss-query-dtcache select --element=CERN-RAW
Traceback (most recent call last):
  File "/afs/cern.ch/lhcb/software/releases/DIRAC/DIRAC_v6r14p22/scripts/dirac-rss-query-dtcache", line 367, in <module>
    run( args, switchDict )
  File "/afs/cern.ch/lhcb/software/releases/DIRAC/DIRAC_v6r14p22/scripts/dirac-rss-query-dtcache", line 344, in run
    result = eval( query + '( switchDict )' )
  File "<string>", line 1, in <module>
  File "/afs/cern.ch/lhcb/software/releases/DIRAC/DIRAC_v6r14p22/scripts/dirac-rss-query-dtcache", line 267, in select
    result['output'] = [ dict( zip( output[ 'Columns' ], dt ) ) for dt in output[ 'Value' ] ]
KeyError: 'Value'
``

**Comment by vipersec** [comment]
Do you get this error while the `ResourceStatus/ResourceManagement` service is running?

**Comment by fstagni** [comment]
Yes I get this error in the production environment (which uses DIRAC 
v6r14). Maybe this is corrected already in v6r15, not sure though.

**Comment by vipersec** [comment]
I created a pull request here: https://github.com/DIRACGrid/DIRAC/pull/2852
