### ISSUE TITLE
Exception when unauthorized query dirac-rss-set-token

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#2994]
dirac-rss-set-token --name=IMPERIAL-USER --element=Resource --reason="I need no reason"
Unauthorized query 
Traceback (most recent call last):
  File "/opt/dirac/versions/v8r3-pre14_1465482140/DIRAC/ResourceStatusSystem/scripts/dirac-rss-set-token.py", line 202, in <module>
    main()
  File "/opt/dirac/versions/v8r3-pre14_1465482140/DIRAC/ResourceStatusSystem/scripts/dirac-rss-set-token.py", line 188, in main
    DIRACExit( res[ 'Message' ] )
  File "/opt/dirac/versions/v8r3-pre14_1465482140/DIRAC/__init__.py", line 189, in exit
    ExitCallback.execute( exitCode, [] )
  File "/opt/dirac/versions/v8r3-pre14_1465482140/DIRAC/Core/Utilities/ExitCallback.py", line 27, in execute
    os._exit( exitCode )
TypeError: an integer is required

**Comment by vipersec** [comment]
@chaen Do you get this error while dirac-service ResourceStatus/ResourceStatus is running?

**Comment by chaen** [comment]
Yes, I am pretty sure you can reproduce it straight forward

**Comment by vipersec** [comment]
I ask because I'm getting the exact same error only when `ResourceStatus/ResourceStatus` is not running. Did you run the command locally in your machine or in the certification test machine?

**Comment by chaen** [comment]
Against the certification machine, from the certification machine.
Did you see the message at the beginning ? ```Unauthorized query```. This is typically a server side error, so yes, the service is running. 

Here is the debug call
```
dirac-rss-set-token --name=GRIDKA-USER --element=Resource --reason="blabla" -ddd
2016-06-17 13:26:29 UTC Framework[Pv9O]  DEBUG: dirac.cfg should be at /opt/dirac/versions/v8r3-pre14_1465482140/etc/dirac.cfg
2016-06-17 13:26:29 UTC Framework[Pv9O]  DEBUG: CFG merged 
2016-06-17 13:26:29 UTC Framework[Pv9O]  DEBUG: Updating configuration internals 
2016-06-17 13:26:29 UTC Framework[Pv9O]  DEBUG: Updating configuration internals 
Parsing command line 
CFG merged 
Updating configuration internals 
2016-06-17 13:26:30 UTC dirac-rss-set-token[Pv9O]  DEBUG: Refreshing configuration... 
2016-06-17 13:26:30 UTC dirac-rss-set-token[Pv9O]  DEBUG: Refreshing from list ['dips://lhcb-conf-dirac.cern.ch:9135/Configuration/Server'] 
2016-06-17 13:26:30 UTC dirac-rss-set-token[Pv9O]  DEBUG: Randomized server list is dips://lhcb-conf-dirac.cern.ch:9135/Configuration/Server 
2016-06-17 13:26:30 UTC dirac-rss-set-token[Pv9O]  DEBUG: Already given a valid url dips://lhcb-conf-dirac.cern.ch:9135/Configuration/Server
2016-06-17 13:26:30 UTC dirac-rss-set-token[Pv9O]  DEBUG:  Trying to refresh from dips://lhcb-conf-dirac.cern.ch:9135/Configuration/Server
2016-06-17 13:26:30 UTC dirac-rss-set-token[Pv9O]  DEBUG: Connecting to: dips://lhcb-conf-dirac.cern.ch:9135/Configuration/Server 
2016-06-17 13:26:30 UTC dirac-rss-set-token[Pv9O]  DEBUG: Using proxy /tmp/x509up_u56212 
2016-06-17 13:26:30 UTC dirac-rss-set-token[Pv9O]  DEBUG: CAs location is /etc/grid-security/certificates 
2016-06-17 13:26:30 UTC dirac-rss-set-token[Pv9O]  DEBUG: Loaded 98 CAs [198 CRLs] 
2016-06-17 13:26:30 UTC dirac-rss-set-token[Pv9O]   VERB: Connection timeout set to:  1
2016-06-17 13:26:30 UTC dirac-rss-set-token[Pv9O]  DEBUG:  Authenticated peer (/DC=ch/DC=cern/OU=computers/CN=lbvobox18.cern.ch)
2016-06-17 13:26:30 UTC dirac-rss-set-token[Pv9O]  DEBUG: New session connecting to server at ('lhcb-conf-dirac.cern.ch', 9135) 
2016-06-17 13:26:30 UTC dirac-rss-set-token[Pv9O]  DEBUG: New connection -> 128.142.152.39:9135 
2016-06-17 13:26:30 UTC dirac-rss-set-token[Pv9O]  DEBUG: Closing socket 
2016-06-17 13:26:30 UTC dirac-rss-set-token[Pv9O]  DEBUG: New version available Updating to version 2016-06-17 09:35:59.915745...
2016-06-17 13:26:31 UTC dirac-rss-set-token[Pv9O]  DEBUG: Updating configuration internals 
2016-06-17 13:26:31 UTC dirac-rss-set-token[Pv9O]  DEBUG: Updated to version 2016-06-17 09:35:59.915745 
2016-06-17 13:26:31 UTC Framework//opt/dirac/versions/v8r3-pre14_1465482140/DIRAC/ResourceStatusSystem/scripts/dirac-rss-set-token.py[Pv9O]  DEBUG: The switches used are: 
2016-06-17 13:26:31 UTC Framework//opt/dirac/versions/v8r3-pre14_1465482140/DIRAC/ResourceStatusSystem/scripts/dirac-rss-set-token.py[Pv9O]  DEBUG: ('reason', 'blabla') 
2016-06-17 13:26:31 UTC Framework//opt/dirac/versions/v8r3-pre14_1465482140/DIRAC/ResourceStatusSystem/scripts/dirac-rss-set-token.py[Pv9O]  DEBUG: ('statusType', None) 
2016-06-17 13:26:31 UTC Framework//opt/dirac/versions/v8r3-pre14_1465482140/DIRAC/ResourceStatusSystem/scripts/dirac-rss-set-token.py[Pv9O]  DEBUG: ('name', 'GRIDKA-USER') 
2016-06-17 13:26:31 UTC Framework//opt/dirac/versions/v8r3-pre14_1465482140/DIRAC/ResourceStatusSystem/scripts/dirac-rss-set-token.py[Pv9O]  DEBUG: ('releaseToken', False) 
2016-06-17 13:26:31 UTC Framework//opt/dirac/versions/v8r3-pre14_1465482140/DIRAC/ResourceStatusSystem/scripts/dirac-rss-set-token.py[Pv9O]  DEBUG: ('element', 'Resource') 
2016-06-17 13:26:31 UTC dirac-rss-set-token[Pv9O]  DEBUG: Discovering URL for service ResourceStatus/ResourceStatus -> dips://lhcb-cert-dirac.cern.ch:9160/ResourceStatus/ResourceStatus
2016-06-17 13:26:31 UTC dirac-rss-set-token[Pv9O]  DEBUG: Calling select, with 
2016-06-17 13:26:31 UTC dirac-rss-set-token[Pv9O]  DEBUG:  params {'status': None, 'lastCheckTime': None, 'dateEffective': None, 'tokenExpiration': None, 'reason': None, 'tokenOwner': None, 'elementType': None, 'statusType': None, 'name': 'GRIDKA-USER'} 
2016-06-17 13:26:31 UTC dirac-rss-set-token[Pv9O]  DEBUG:  meta {'table': 'ResourceStatus', 'columns': ['StatusType', 'TokenOwner']} 
2016-06-17 13:26:31 UTC dirac-rss-set-token[Pv9O]  DEBUG: Connecting to: dips://lhcb-cert-dirac.cern.ch:9160/ResourceStatus/ResourceStatus 
2016-06-17 13:26:31 UTC dirac-rss-set-token[Pv9O]  DEBUG: Using proxy /tmp/x509up_u56212 
2016-06-17 13:26:31 UTC dirac-rss-set-token[Pv9O]   VERB: Connection timeout set to:  1
2016-06-17 13:26:32 UTC dirac-rss-set-token[Pv9O]  DEBUG:  Authenticated peer (/DC=ch/DC=cern/OU=computers/CN=lbtestvobox.cern.ch)
2016-06-17 13:26:32 UTC dirac-rss-set-token[Pv9O]  DEBUG: New session connecting to server at ('lhcb-cert-dirac.cern.ch', 9160) 
2016-06-17 13:26:32 UTC dirac-rss-set-token[Pv9O]  DEBUG: New connection -> 2001:1458:301:48::100:46:9160 
2016-06-17 13:26:32 UTC dirac-rss-set-token[Pv9O]  DEBUG: Closing socket 
2016-06-17 13:26:32 UTC Framework//opt/dirac/versions/v8r3-pre14_1465482140/DIRAC/ResourceStatusSystem/scripts/dirac-rss-set-token.py[Pv9O]   INFO: New token : chaen until 2016-06-18 13:26:32 
2016-06-17 13:26:32 UTC dirac-rss-set-token[Pv9O]  DEBUG: Calling modify, with 
2016-06-17 13:26:32 UTC dirac-rss-set-token[Pv9O]  DEBUG:  params {'status': None, 'lastCheckTime': None, 'dateEffective': None, 'tokenExpiration': datetime.datetime(2016, 6, 18, 13, 26, 32), 'reason': 'blabla', 'tokenOwner': 'chaen', 'elementType': None, 'statusType': 'CheckAccess', 'name': 'GRIDKA-USER'} 
2016-06-17 13:26:32 UTC dirac-rss-set-token[Pv9O]  DEBUG:  meta {'onlyUniqueKeys': True, 'table': 'ResourceStatus'} 
2016-06-17 13:26:32 UTC dirac-rss-set-token[Pv9O]  DEBUG: Connecting to: dips://lhcb-cert-dirac.cern.ch:9160/ResourceStatus/ResourceStatus 
2016-06-17 13:26:32 UTC dirac-rss-set-token[Pv9O]  DEBUG: Using proxy /tmp/x509up_u56212 
2016-06-17 13:26:32 UTC dirac-rss-set-token[Pv9O]   VERB: Connection timeout set to:  1
2016-06-17 13:26:32 UTC dirac-rss-set-token[Pv9O]  DEBUG:  Authenticated peer (/DC=ch/DC=cern/OU=computers/CN=lbtestvobox.cern.ch)
2016-06-17 13:26:32 UTC dirac-rss-set-token[Pv9O]  DEBUG: New session connecting to server at ('lhcb-cert-dirac.cern.ch', 9160) 
2016-06-17 13:26:32 UTC dirac-rss-set-token[Pv9O]  DEBUG: New connection -> 2001:1458:301:48::100:46:9160 
2016-06-17 13:26:32 UTC dirac-rss-set-token[Pv9O]  DEBUG: Closing socket 
2016-06-17 13:26:32 UTC Framework//opt/dirac/versions/v8r3-pre14_1465482140/DIRAC/ResourceStatusSystem/scripts/dirac-rss-set-token.py[Pv9O]  ERROR: Unauthorized query 
Traceback (most recent call last):
  File "/opt/dirac/versions/v8r3-pre14_1465482140/DIRAC/ResourceStatusSystem/scripts/dirac-rss-set-token.py", line 202, in <module>
    main()
  File "/opt/dirac/versions/v8r3-pre14_1465482140/DIRAC/ResourceStatusSystem/scripts/dirac-rss-set-token.py", line 188, in main
    DIRACExit( res[ 'Message' ] )
  File "/opt/dirac/versions/v8r3-pre14_1465482140/DIRAC/__init__.py", line 189, in exit
    ExitCallback.execute( exitCode, [] )
  File "/opt/dirac/versions/v8r3-pre14_1465482140/DIRAC/Core/Utilities/ExitCallback.py", line 27, in execute
    os._exit( exitCode )
TypeError: an integer is required
```

**Comment by vipersec** [comment]
@chaen 
The required integer value was fixed with https://github.com/DIRACGrid/DIRAC/pull/3004
After investigation I have come to the conclusion that `Unauthorized query` is a user privilege issue.

**Comment by zmathe** [comment]
What I can see from the log is the 2016-06-17 13:26:31 UTC dirac-rss-set-token[Pv9O]  DEBUG: Using proxy /tmp/x509up_u56212  proxy used and the proxy does not has the correct property.
@chaen Which proxy are you using? What is the group?

**Comment by chaen** [comment]
I know that it is a authorization issue, I did it with my user proxy instead of the admin one. That's not the problem. The problem was the exception following
