### ISSUE TITLE
Verify a DEncode implementation that uses json

### ISSUE THREAD

**Issue by zmathe** [DIRACGrid/DIRAC#3015]
I have noticed that if we send S_OK(set) via RPC the service throw an exception and the thread keep running and the client keep connected. After I restart the service I receive the following error in server side:
2016-06-24 15:00:29 UTC Bookkeeping/TestBookkeepingManager NOTICE: Returning response ([::ffff:137.138.188.94]:56429)[lhcb_user:zmathe](0.02 secs) OK
2016-06-24 15:00:29 UTC Bookkeeping/TestBookkeepingManager EXCEPT: Exception while executing handler action
2016-06-24 15:00:29 UTC Bookkeeping/TestBookkeepingManager EXCEPT: == EXCEPTION == KeyError
2016-06-24 15:00:29 UTC Bookkeeping/TestBookkeepingManager EXCEPT:
2016-06-24 15:00:29 UTC Bookkeeping/TestBookkeepingManager EXCEPT: KeyError: <type 'set'>
2016-06-24 15:00:29 UTC Bookkeeping/TestBookkeepingManager EXCEPT: ===============
2016-06-24 15:00:29 UTC Bookkeeping/TestBookkeepingManager  ERROR: Error processing proposal Server error while executing action: <type 'set'>
and the client is hanging (which means it keeps connected).
After I restarted the service I got: Exception while reading from peer: (-1, 'Unexpected EOF'). 

It is not the case that we want to return a set, but it the exception must be handled correctly. So the exception must be returned to the client and the connection must be closed.
So, we have two problems DEncode and DISET

1.DEncode: easy to fix it:
For example:

> > > from DIRAC.Core.Utilities                           import DEncode
> > > DEncode.encode(set([2,1]))
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/opt/dirac/pro/DIRAC/Core/Utilities/DEncode.py", line 229, in encode
> > >     g_dEncodeFunctions[ type( uObject ) ](uObject, eList)
> > > KeyError: <type 'set'>
1. It is deep in DISET

**Comment by fstagni** [comment]
The question here is: should we fix Decode/DEncode, or should we move to 
json encoding, as already discussed some time ago?

**Comment by zmathe** [comment]
I would say better to move to json and fix the exception. I mean if an exception happen during the data transfer preparation, DISET must close the connection and release the thread...

**Comment by chaen** [comment]
I vote for json as well

**Comment by atsareg** [comment]
As was already discussed, the DEncode should be reimplemented using json to keep the same interface and backward compatibility. Are sets supported by json ?

**Comment by chaen** [comment]
I think this can be closed no ? We have the implementation

**Comment by fstagni** [comment]
I believe so.
