### ISSUE TITLE
Operation failed: URL for service Framework/UserProfileManager not found.

### ISSUE THREAD

**Issue by iarspider** [DIRACGrid/DIRAC#3203]
A popup with message "Operation failed: URL for service Framework/UserProfileManager not found." is shown when logging into a fresh installation of Dirac v6r16p3. Related excerpt WebAppfrom log:
```
2016-12-06 15:38:41 UTC WebApp/RootHandler  ERROR: Request ended in error:
2016-12-06 15:38:41 UTC WebApp/RootHandler  ERROR:   Traceback (most recent call last):
2016-12-06 15:38:41 UTC WebApp/RootHandler  ERROR: 
2016-12-06 15:38:41 UTC WebApp/RootHandler  ERROR:     File "/opt/dirac/versions/v6r16p3_1481037500/Linux_x86_64_glibc-2.17/lib/python2.7/site-packages/tornado/web.py", line 1469, in _execute
2016-12-06 15:38:41 UTC WebApp/RootHandler  ERROR:     result = yield result
2016-12-06 15:38:41 UTC WebApp/RootHandler  ERROR: 
2016-12-06 15:38:41 UTC WebApp/RootHandler  ERROR:     File "/opt/dirac/versions/v6r16p3_1481037500/Linux_x86_64_glibc-2.17/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
2016-12-06 15:38:41 UTC WebApp/RootHandler  ERROR:     value = future.result()
2016-12-06 15:38:41 UTC WebApp/RootHandler  ERROR: 
2016-12-06 15:38:41 UTC WebApp/RootHandler  ERROR:     File "/opt/dirac/versions/v6r16p3_1481037500/Linux_x86_64_glibc-2.17/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
2016-12-06 15:38:41 UTC WebApp/RootHandler  ERROR:     raise_exc_info(self._exc_info)
2016-12-06 15:38:41 UTC WebApp/RootHandler  ERROR: 
2016-12-06 15:38:41 UTC WebApp/RootHandler  ERROR:     File "/opt/dirac/versions/v6r16p3_1481037500/Linux_x86_64_glibc-2.17/lib/python2.7/site-packages/tornado/gen.py", line 1024, in run
2016-12-06 15:38:41 UTC WebApp/RootHandler  ERROR:     yielded = self.gen.send(value)
2016-12-06 15:38:41 UTC WebApp/RootHandler  ERROR: 
2016-12-06 15:38:41 UTC WebApp/RootHandler  ERROR:     File "/opt/dirac/versions/v6r16p3_1481037500/WebAppDIRAC/WebApp/handler/UPHandler.py", line 120, in web_listAppState
2016-12-06 15:38:41 UTC WebApp/RootHandler  ERROR:     raise WErr.fromSERROR( result )
2016-12-06 15:38:41 UTC WebApp/RootHandler  ERROR: 
2016-12-06 15:38:41 UTC WebApp/RootHandler  ERROR:   WErr
2016-12-06 15:38:41 UTC WebApp/RootHandler  ERROR: 
2016-12-06 15:38:41 UTC WebApp/Web  ERROR: 500 POST /DIRAC/s:MyDIRAC-Production/g:user/UP/listAppState (128.141.125.223) admin@user (/C=RU/O=RDIG/OU=users/OU=ihep.su/CN=Ivan Razumov) 25.92ms
```

**Comment by zmathe** [comment]
UserProfile service is storing information related to the user selection. I never tried but WebApp may work without UserProfile. But you can easily install the service...

**Comment by iarspider** [comment]
Installing the service through CLI doesn't work: "Unauthorized query".

I have tried to install Dirac from scratch (new config: https://gist.github.com/iarspider/ede73e0a4aba5529f756a00a80724402), but installation fails with "KeyError: username". Full installation log: https://gist.github.com/iarspider/1af444e537069dc50d10cffb85afa585

**Comment by iarspider** [comment]
Installation from scratch was failing because of old x509 proxy file in tmp.

**Comment by iarspider** [comment]
Fixed it myself.
