### ISSUE TITLE
[v6r17p18] Exception in WorkflowTaskAgent without bulk submission

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#3334]
I get an exception in the WorkflowTaskAgent in v6r17p18
```
2017-05-09 14:44:34 UTC Transformation/WorkflowTaskAgent EXCEPT:  [Thread14] [400953] ._execute Exception executing operation submitTasks
2017-05-09 14:44:34 UTC Transformation/WorkflowTaskAgent EXCEPT: == EXCEPTION == TypeError
2017-05-09 14:44:34 UTC Transformation/WorkflowTaskAgent EXCEPT:   File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 182, in deepcopy
2017-05-09 14:44:34 UTC Transformation/WorkflowTaskAgent EXCEPT:     rv = reductor(2)
2017-05-09 14:44:34 UTC Transformation/WorkflowTaskAgent EXCEPT:
2017-05-09 14:44:34 UTC Transformation/WorkflowTaskAgent EXCEPT: TypeError: can't pickle thread.lock objects
2017-05-09 14:44:34 UTC Transformation/WorkflowTaskAgent EXCEPT: ===============
```
I put in extra printout to get the full stacktrace
```
Traceback (most recent call last):
  File "/opt/dirac/pro/DIRAC/TransformationSystem/Agent/TaskManagerAgentBase.py", line 275, in _execute
    res = getattr( self, operation )( transIDOPBody, clients )
  File "/opt/dirac/pro/DIRAC/TransformationSystem/Agent/TaskManagerAgentBase.py", line 533, in submitTasks
    self.bulkSubmissionFlag )
  File "/opt/dirac/pro/DIRAC/TransformationSystem/Client/TaskManager.py", line 481, in prepareTransformationTasks
    return self.__prepareTransformationTasks( transBody, taskDict, owner, ownerGroup, ownerDN )
  File "/opt/dirac/pro/DIRAC/TransformationSystem/Client/TaskManager.py", line 604, in __prepareTransformationTasks
    oJob = copy.deepcopy( oJobTemplate )
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/copy.py", line 182, in deepcopy
    rv = reductor(2)
TypeError: can't pickle thread.lock objects
********************************************************************************
```
The problem is this deepcopy of the job object
https://github.com/DIRACGrid/DIRAC/blob/integration/TransformationSystem/Client/TaskManager.py#L604
```
oJob = copy.deepcopy( oJobTemplate )
```
printing out `vars(oJobTemplate)` made me suspect the `log` member of the object, so I did
```
        oJobTemplate.log = None
        oJob = copy.deepcopy( oJobTemplate )
        oJob.log = gLogger.getSubLogger("jobLog")
```
Which solves the problem.
So:
* Is the non-bulk submission still needed, or can we just drop that part and make everyone use bulksubmission?
* Or should I make a pull request with my solution?

**Comment by fstagni** [comment]
The `oJobTemplate` is created with
```
oJobTemplate = self.jobClass( transBody )
```
which means for your case the `ILCJob` class. How are you defining the `log` member there?

**Comment by andresailer** [comment]
If I print the Job object out I get 
```
<DIRAC.Interfaces.API.Job.Job object at 0x7f7830802490>
```
So I am assuming this is the DIRAC Job Object.
In any case in the ILCDIRAC Job Class init
```
    self.log = gLogger.getSubLogger("ILCJob")
```

**Comment by andresailer** [comment]
This is the printout of `vars(objTemplate)`
```
{'_printFormattedDictList': <function _printFormattedDictList at 0x7fea21f65140>,
 '_siteSet': set([SNIPPED]),
 'addToInputData': [],
 'addToInputSandbox': [],
 'addToOutputSandbox': [],
 'dbg': True,
 'diracInfo': 'v26r0p8',
 'errorDict': {},
 'executable': '$DIRACROOT/scripts/dirac-jobexec',
 'group': 'ilc',
 'log': <DIRAC.FrameworkSystem.private.logging.SubSystemLogger.SubSystemLogger object at 0x7fea20608e50>,
 'logLevel': 'info',
 'name': 'Name',
 'numberOfParameters': 0,
 'origin': 'DIRAC',
 'owner': 'NotSpecified',
 'pPrint': <pprint.PrettyPrinter instance at 0x7fea20263710>,
 'parameterSeqs': {},
 'parametricWFArguments': {},
 'priority': 1,
 'script': 'SNIPPED',
 'section': 'API',
 'setup': 'ILC-Development',
 'site': 'ANY',
 'stderr': 'std.err',
 'stdout': 'std.out',
 'stepCount': 0,
 'type': 'User',
 'wfArguments': {},
 'workflow': {'descr_short': '',
              'description': '',
              'name': 'hzqq_350_test_v27r0_7_beamrecoil_e1F_E1F',
              'origin': '',
              'type': '',
              'version': '0.0'}}
```
PS: Note, none of the ILCDIRAC Job attributes are present, so pretty sure it is pure DIRAC.

**Comment by fstagni** [comment]
Ah I see. In `LHCbJob` we don't re-create the `log` member so I am puzzled at why we don't see the same as you. Also we didn't hear complains from others... so right now I have no good suggestions. I don't so much like your "fix" to be honest.

Now, partially un-related but originated from this thread:
- question: is this what you want? I mean, you are submitting Jobs created from class `DIRAC.Interfaces.API.Job.Job` instead of jobs created from an extension of it. In most cases this is safe, but not necessarily recommended.
- And before I forget again: the non-bulk submission is still needed (and it's "safer" so it is still used in LHCb)

**Comment by andresailer** [comment]
Ok, I thought you are using bulk submission.

Things have been working so far, so I never had to think about what kind of job object is created.

I can remove the re-instantiation of the log member and see what happens.

**Comment by andresailer** [comment]
This http://stackoverflow.com/a/2999833 would be the proper solution to prevent deep-copying of the log member.
And that also solves the problem I see.

**Comment by fstagni** [comment]
I see, looks good. Do you want to prepare a PR for that? In the same thread there might be a better solution: http://stackoverflow.com/a/26063379/7031145

**Comment by andresailer** [comment]
Do you want me to put that in the API class, or in the Job class?

**Comment by fstagni** [comment]
It should be safe in the API class, I believe
