### ISSUE TITLE
v6r20p3: delete job function fails

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#3729]
The traceback is below. We think that it's trying to kill the matching pilot job, but the pilot job reference appears to be returning a number rather than a dictionary.

```
2018-06-20 13:30:31 UTC WorkloadManagement/JobManager ERROR: Uncaught exception when serving RPC Function deleteJob
Traceback (most recent call last):
  File "/opt/dirac/DIRAC/Core/DISET/RequestHandler.py", line 270, in __RPCCallFunction
    uReturnValue = oMethod(*args)
  File "/opt/dirac/DIRAC/WorkloadManagementSystem/Service/JobManagerHandler.py", line 469, in export_deleteJob
    return self.__kill_delete_jobs(jobIDs, RIGHT_DELETE)
  File "/opt/dirac/DIRAC/WorkloadManagementSystem/Service/JobManagerHandler.py", line 430, in __kill_delete_jobs
    result = self.__deleteJob(jobID)
  File "/opt/dirac/DIRAC/WorkloadManagementSystem/Service/JobManagerHandler.py", line 349, in __deleteJob
    res = gPilotAgentsDB.getJobsForPilot(pilot['PilotID'])
TypeError: 'long' object has no attribute '__getitem__'
```

**Comment by fstagni** [comment]
Fixed in https://github.com/DIRACGrid/DIRAC/pull/3755 (v6r20p6 certainly includes it)
