### ISSUE TITLE
v6r20: uncaught exception in getTransformationDirectories

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#3731]
When testing the transformation system using the tutorial I naively set the OutputDirectories as a string  
```
outputPath = os.path.join('/skatelescope.eu/user',owner[0],owner,'mandelbrot/images/raw5')
t.transClient.setTransformationParameter(transid, "OutputDirectories", outputPath)
```
This results in a uncaught exception in the TransformationCleaningAgent:
```
2018-06-21 11:48:46 UTC Transformation/TransformationCleaningAgent ERROR: Agent exception while calling method <bound method TransformationCleaningAgent.execute of <TransformationCleaningAgent.TransformationCleaningAgent object at 0x7f0570b2eb10>>
Traceback (most recent call last):
  File "/opt/dirac/DIRAC/Core/Base/AgentModule.py", line 320, in am_secureCall
    result = functor( *args )
  
File "/opt/dirac/DIRAC/TransformationSystem/Agent/TransformationCleaningAgent.py", line 153, in 
    res = self.cleanTransformation(transDict['TransformationID'])
  File "/opt/dirac/DIRAC/TransformationSystem/Agent/TransformationCleaningAgent.py", line 432, in cleanTransformation
    res = self.getTransformationDirectories(transID)
  File "/opt/dirac/DIRAC/TransformationSystem/Agent/TransformationCleaningAgent.py", line 207, in getTransformationDirectories
    transDirectories = ast.literal_eval(res['Value'])
  File "/opt/dirac/Linux_x86_64_glibc-2.12/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/opt/dirac/Linux_x86_64_glibc-2.12/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    /skatelescope.eu/user/d/daniela.bauer/mandelbrot/images/raw5
    ^
SyntaxError: invalid syntax
```
This leaves the transformation in some kind of cleaning limbo.

**Comment by zmathe** [comment]
It is fixed in #3726
