### ISSUE TITLE
v6r20: Transformation System: file replication fails due "None" != None

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#3746]
I tried to copy a batch of files via the transformation system. It failed with:

```
2018-06-25 11:20:56 UTC Transformation/RequestTaskAgent ERROR:  [Thread12] [20] ._execute Exception executing operation updateTaskStatus
Traceback (most recent call last):
  File "/opt/dirac/DIRAC/TransformationSystem/Agent/TaskManagerAgentBase.py", line 283, in _execute
    res = getattr(self, operation)(transIDOPBody, clients)
  File "/opt/dirac/DIRAC/TransformationSystem/Agent/TaskManagerAgentBase.py", line 352, in updateTaskStatus
    submittedTaskStatus = clients['TaskManager'].getSubmittedTaskStatus(taskChunk)
  File "/opt/dirac/DIRAC/TransformationSystem/Client/TaskManager.py", line 353, in getSubmittedTaskStatus
    if taskDict['ExternalID'] and int(taskDict['ExternalID']):
ValueError: invalid literal for int() with base 10: 'None'
```
We currently have a workaround implemented:
```
--- a/TransformationSystem/Client/TaskManager.py
+++ b/TransformationSystem/Client/TaskManager.py
@@ -350,7 +350,7 @@ class RequestTasks(TaskBase):
     for taskDict in taskDicts:
       oldStatus = taskDict['ExternalStatus']
       # ExternalID is normally a string
-      if taskDict['ExternalID'] and int(taskDict['ExternalID']):
+      if taskDict['ExternalID'] and taskDict['ExternalID'] != 'None' and int(taskDict['ExternalID']):
         newStatus = self.requestClient.getRequestStatus(taskDict['ExternalID'])
         if not newStatus['OK']:
           log = self._logVerbose if 'not exist' in newStatus['Message'] else self._logWarn
@@ -390,6 +390,8 @@ class RequestTasks(TaskBase):
     for taskDict in res['Value']:
       taskID = taskDict['TaskID']
       externalID = taskDict['ExternalID']
+      if externalID == 'None':
+        externalID = None
       # Only consider tasks that are submitted, ExternalID is a string
       if taskDict['ExternalStatus'] != 'Created' and externalID and int(externalID):
         requestFiles[externalID] = taskFiles[taskID]
```
A proper fix would be better though.

**Comment by fstagni** [comment]
Sorry for the late reply on this. 
First, I'd like to know if you still see this error, even after upgrading to the latest v6r20 release (which Andrei did today). Second, I believe this error is due a mis-configuration on your side (not that the instructions are perfect...). That "ExternalID" is holding, in this case, the "RequestID" (the ID of the Request in the Request Management DB, can be found in ReqDB/Request MySQL table) that is managing the task.

**Comment by marianne013** [comment]
We ran it again against v6r20p6 and I didn't see the error. Having said this, I did not change the configuration nor the transformation (it's a script and I just resubmitted it with a new name for the transformation), so it's not clear to me what kind of mis-configuration I would have made. Could you elaborate, please ?

**Comment by fstagni** [comment]
Our configuration is quite complex:
```
        RequestTaskAgent
        {
          PollingTime = 60
          LogLevel = INFO
          LogBackends = stdout
          LogBackends += server
          CheckReserved = Exists
          MonitorTasks = Exists
          SubmitTasks = Exists
          MonitorFiles = Exists
          TasksPerLoop = 500
          #@@-phicharp@lhcb_admin - 2017-03-27 06:38:45
          TaskUpdateChunkSize = 100
          #@@-phicharp@lhcb_admin - 2017-03-27 15:29:39
          TaskUpdateStatus = Scheduled
          TaskUpdateStatus += Submitted
          TaskUpdateStatus += Waiting
          TaskUpdateStatus += Assigned
          UpdateTasksTransformationStatus = Active
          UpdateTasksTransformationStatus += Idle
          UpdateTasksTransformationStatus += Completed
          UpdateTasksTransformationStatus += Stopped
          UpdateTasksStatus = Active
          UpdateTasksStatus += Idle
          UpdateTasksStatus += Completed
          UpdateTasksStatus += Stopped
        }
```
so, maybe yours was missing some parts. Anyway, I will close this ticket now. Please open again if you see more issues.
