### ISSUE TITLE
[v6r20] Exception in SiteInspectorAgent (RSS CSHelpers.getSiteElements)

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#3869]
The HEAD of rel-v6r20 (v6r20p16) gives an exception

```
2018-10-25 06:03:54 UTC ResourceStatus/SiteInspectorAgent ERROR: Exception in thread
Traceback (most recent call last):
  File "/opt/dirac/pro/DIRAC/Core/Utilities/ThreadPool.py", line 161, in process
    self.__jobResult = self.__jobFunction( *self.__jobArgs, **self.__jobKwArgs )
  File "/opt/dirac/pro/DIRAC/ResourceStatusSystem/Agent/SiteInspectorAgent.py", line 164, in _execute
    resEnforce = pep.enforce( site )
  File "/opt/dirac/pro/DIRAC/ResourceStatusSystem/PolicySystem/PEP.py", line 111, in enforce
    resDecisions = self.pdp.takeDecision()
  File "/opt/dirac/pro/DIRAC/ResourceStatusSystem/PolicySystem/PDP.py", line 145, in takeDecision
    singlePolicyResults = self._runPolicies( policiesThatApply )
  File "/opt/dirac/pro/DIRAC/ResourceStatusSystem/PolicySystem/PDP.py", line 212, in _runPolicies
    policyDict )
  File "/opt/dirac/pro/DIRAC/ResourceStatusSystem/PolicySystem/PolicyCaller.py", line 75, in policyInvocation
    evaluationResult = self.policyEvaluation( policy, command )
  File "/opt/dirac/pro/DIRAC/ResourceStatusSystem/PolicySystem/PolicyCaller.py", line 90, in policyEvaluation
    evaluationResult = policy.evaluate()
  File "/opt/dirac/pro/DIRAC/ResourceStatusSystem/PolicySystem/PolicyBase.py", line 41, in evaluate
    commandResult = self.command.doCommand()
  File "/opt/dirac/pro/DIRAC/ResourceStatusSystem/Command/Command.py", line 57, in doCommand
    result = self.doCache()
  File "/opt/dirac/pro/DIRAC/ResourceStatusSystem/Command/PropagationCommand.py", line 32, in doCache
    elements = CSHelpers.getSiteElements(site)
  File "/opt/dirac/pro/DIRAC/ResourceStatusSystem/Utilities/CSHelpers.py", line 393, in getSiteElements
    resources = resources + ce
TypeError: unsupported operand type(s) for +: 'set' and 'list'
```

I am not sure what getSiteElements should return, a list or a set.

**Comment by fstagni** [comment]
Fixed in https://github.com/DIRACGrid/DIRAC/pull/3863
