### ISSUE TITLE
[MAYBE A BUG] Threading initialization of M2Crypto incorrect

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#4444]
We observed the following exception:
```
2020-02-11 09:18:31 UTC Transformation/WorkflowTaskAgent-MCSimulation ERROR: 
Traceback (most recent call last):
  File "/opt/dirac/versions/v10r0-pre4_1575560385/DIRAC/Core/DISET/private/BaseClient.py", line 453, in _connect
    retVal = transport.initAsClient()
  File "/opt/dirac/versions/v10r0-pre4_1575560385/DIRAC/Core/DISET/private/Transports/M2SSLTransport.py", line 92, in initAsCl
ient
    self.oSocket.connect((host, port))
  File "/opt/dirac/pro/diracos/usr/lib64/python2.7/site-packages/M2Crypto/SSL/Connection.py", line 312, in connect
    self.host if self.host else self.addr[0]):
  File "/opt/dirac/pro/diracos/usr/lib64/python2.7/site-packages/M2Crypto/SSL/Checker.py", line 125, in __call__
    fieldName='subjectAltName')
WrongHost: Peer certificate subjectAltName does not match host, expected lhcbvoboxcertif00.cern.ch, got DNS:lhcbvoboxcertif01.
cern.ch, DNS:lhcb-cert-conf-dirac.cern.ch
```
So clearly something not threadsafe.

Looking at https://its.cern.ch/jira/browse/FTS-714 and https://gitlab.cern.ch/fts/fts-rest/commit/95a24fed672399f83fbf33b705756069357eed02 we may need to add this call in the constructor

https://github.com/DIRACGrid/DIRAC/blob/d1cce9b154c25fc8ea00ecf363dc1eb63c8a3563/Core/DISET/private/Transports/M2SSLTransport.py#L19

**Comment by fstagni** [comment]
Is this still there?

**Comment by fstagni** [comment]
I bump this issue since it's marked with milestone "v7r0". Are there updates?

**Comment by chaen** [comment]
I did not work on it since I was not able to reproduce so far, but I keep it in mind

**Comment by chaen** [comment]
Got it !!!!! It is in M2Crypto. 
Done an MR for it: https://gitlab.com/m2crypto/m2crypto/-/merge_requests/246
