### ISSUE TITLE
[MAYBE] Retry mechanism not working when SSL times out

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#4473]
I just keep it here for my memory, but I am not sure how we end up retrying URLs (as the logs seem to indicate) as the exception is caught higher

```
2020-03-03 13:28:35 UTC Configuration/GOCDB2CSAgent/Monitoring ERROR: Can't register activities Can't connect to dips://lbcertifdirac70.cern.ch:9142/Framework/Monitoring: SSLError(104, 'Connection reset by peer')
2020-03-03 13:33:57 UTC Configuration/GOCDB2CSAgent WARN: Issue getting socket: <DIRAC.Core.DISET.private.Transports.M2SSLTransport.SSLTransport object at 0x7f73ed3cdb90> : ('dips', 'lbcertifdirac70.cern.ch', 9142, 'Framework/Monitoring') : error(110, 'Connection timed out')
2020-03-03 13:33:57 UTC Configuration/GOCDB2CSAgent WARN: Non-responding URL temporarily banned dips://lbcertifdirac70.cern.ch:9142/Framework/Monitoring
2020-03-03 13:33:57 UTC Configuration/GOCDB2CSAgent INFO: Retry connection : 1 to dips://lbcertifdirac70.cern.ch:9142/Framework/Monitoring
2020-03-03 13:33:57 UTC Configuration/GOCDB2CSAgent INFO: Waiting 2.000000 seconds before retry all service(s)
2020-03-03 13:35:56 UTC Configuration/GOCDB2CSAgent ERROR: 
Traceback (most recent call last):
  File "/opt/dirac/pro/DIRAC/Core/DISET/private/BaseClient.py", line 454, in _connect
    retVal = transport.initAsClient()
  File "/opt/dirac/pro/DIRAC/Core/DISET/private/Transports/M2SSLTransport.py", line 92, in initAsClient
    self.oSocket.connect((host, port))
  File "/opt/dirac/pro/diracos/usr/lib64/python2.7/site-packages/M2Crypto/SSL/Connection.py", line 307, in connect
    ret = self.connect_ssl()
  File "/opt/dirac/pro/diracos/usr/lib64/python2.7/site-packages/M2Crypto/SSL/Connection.py", line 293, in connect_ssl
    return m2.ssl_connect(self.ssl, self._timeout)
SSLError: (104, 'Connection reset by peer')
2020-03-03 13:35:56 UTC Configuration/GOCDB2CSAgent/Monitoring ERROR: Can't register activities Can't connect to dips://lbcertifdirac70.cern.ch:9142/Framework/Monitoring: SSLError(104, 'Connection reset by peer')
```

**Comment by chaen** [comment]
Actually this is maybe still true... It would require though somebody to dig relatively deep in the DISET internals.
