### ISSUE TITLE
[v7r1] Pilot3 expects arguments when submitting JDL

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#4600]
As part of my test suite, I run a very simple jdl using an executable without arguments. When switching to Pilot3 these jobs fail with the following error in the pilot log.
```
2020-05-12 11:52:18 UTC WorkloadManagement/JobAgent ERROR: Agent exception while calling method <bound method JobAgent.execute of <JobAgent.JobAgent object at 0x2b2b930bc810>>
Traceback (most recent call last):
  File "/srv/localstage/condor/dir_22983/DIRAC_HWk9USpilot/DIRAC/Core/Base/AgentModule.py", line 327, in am_secureCall
    result = functor(*args)
  File "/srv/localstage/condor/dir_22983/DIRAC_HWk9USpilot/DIRAC/WorkloadManagementSystem/Agent/JobAgent.py", line 307, in execute
    params['Arguments'] += ' ' + self.extraOptions
KeyError: 'Arguments'
```
This behaviour is not present for pilot2.

**Comment by fstagni** [comment]
Fixed in https://github.com/DIRACGrid/DIRAC/pull/4601
