### ISSUE TITLE
[v7r1p8]  DIRAC/WorkloadManagementSystem/Utilities/JobParameters.py does not handle 'None' correctly

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#4707]
As it turns out MJF can return and int or a None and both cases should be handled correctly.
```
Traceback (most recent call last):
  File "/mnt/dirac/DIRAC/WorkloadManagementSystem/scripts/dirac-wms-get-wn-parameters.py", line 44, in <module>
    numberOfProcessor = JobParameters.getNumberOfProcessors(Site, ceName, Queue)
  File "/mnt/dirac/DIRAC/WorkloadManagementSystem/Utilities/JobParameters.py", line 68, in getNumberOfProcessors
    numberOfProcessors = getProcessorFromMJF()
  File "/mnt/dirac/DIRAC/WorkloadManagementSystem/Utilities/JobParameters.py", line 32, in getProcessorFromMJF
    return int(getJobFeatures().get('allocated_cpu'))
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by chrisburr** [comment]
Sorry about that, it's been fixed in #4706. Apparently new patch releases will be made today after that PR is merged.
