### ISSUE TITLE
[v7r1] Crash in SiteDirector if CheckPlatform = True

### ISSUE THREAD

**Issue by sfayer** [DIRACGrid/DIRAC#4835]
Hi,

As mentioned at the BiLD meeting today, we see a crash in the SiteDirector code when the CheckPlatform setting is True on v7r1p18 (line numbers may be off a bit as I've added some extra debugging printouts):
```python
Traceback (most recent call last):
  File "/opt/dirac/DIRAC/Core/Base/AgentModule.py", line 327, in am_secureCall
    result = functor(*args)
  File "/opt/dirac/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py", line 475, in execute
    result = self.submitPilots()
  File "/opt/dirac/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py", line 497, in submitPilots
    submit, anySite, jobSites, testSites = self._ifAndWhereToSubmit()
  File "/opt/dirac/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py", line 621, in _ifAndWhereToSubmit
    tqDict = self._getTQDictForMatching()
  File "/opt/dirac/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py", line 698, in _getTQDictForMatching
    platforms = self._getPlatforms()
  File "/opt/dirac/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py", line 721, in _getPlatforms
    result = self.resourcesModule.getCompatiblePlatforms(self.platforms)
  File "/opt/dirac/DIRAC/ConfigurationSystem/Client/Helpers/Resources.py", line 326, in getCompatiblePlatforms
    platforms = list(platform.replace(' ', '') for platform in platforms)
  File "/opt/dirac/DIRAC/ConfigurationSystem/Client/Helpers/Resources.py", line 326, in <genexpr>
    platforms = list(platform.replace(' ', '') for platform in platforms)
AttributeError: 'list' object has no attribute 'replace'
```
It seems on the second (or later) run of execute(), if there is a job waiting, this line returns a list of platforms:
https://github.com/DIRACGrid/DIRAC/blob/ca1da2e3783883574be42aa3b501ad0da686d9c7/WorkloadManagementSystem/Agent/SiteDirector.py#L395

Which then gets appended to the second list:
https://github.com/DIRACGrid/DIRAC/blob/ca1da2e3783883574be42aa3b501ad0da686d9c7/WorkloadManagementSystem/Agent/SiteDirector.py#L402

Resulting in a nested list of platforms, causing the crash later in the code:
`['x86_64_EL7',['x86_64_EL7', 'EL7']]`
(Our platforms names are a little bit different to the traditional DIRAC glibc version platforms, but work exactly the same here).

The obvious fix for this it to just flatten and de-duplicate the list using a set, but I wondered if there was a better fix?

Regards,
Simon

**Comment by fstagni** [comment]
Hi Simon,
there's no better fix than the one you propose. And the bug is there also in v7r0: would you please submit a fix for it, targeting `rel-v7r0`?
Thanks,
Federico
