### ISSUE TITLE
v7r3p9: dirac-admin-sysadmin-cli  show info crashes with backtrace

### ISSUE THREAD

**Issue by raowenqmul** [DIRACGrid/DIRAC#5621]
I'm running a minimal python2 dirac server v7r3p9 and client v7r3p9.

But running dirac-admin-sysadmin-cli  show info crashes with a backtrace.

After getting proxy cert I run: `dirac-admin-sysadmin-cli --host dirac2`
And then show status works but show info crashes... Strange!

```
[dirac2]> show status
  System         Name                Module              Type    Setup Installed Runit Uptime PID
==================================================================================================
1 ResourceStatus ResourceStatus      ResourceStatus      service Setup Installed Run      412 8575
2 Framework      BundleDelivery      BundleDelivery      service Setup Installed Run      406 8660
3 Framework      ComponentMonitoring ComponentMonitoring service Setup Installed Run      424 8405
4 Framework      SystemAdministrator SystemAdministrator service Setup Installed Run      418 8490
5 Framework      UserProfileManager  UserProfileManager  service Setup Installed Run      400 8746
6 Configuration  Server              Server              service Setup Installed Run      449 8312

[dirac2]> show info

Setup: GridPP
Traceback (most recent call last):
 File "/home/owen/dirac2.esc.client/DIRAC/FrameworkSystem/scripts/dirac_admin_sysadmin_cli.py", line 35, in <module>
   main()
 File "/home/owen/dirac2.esc.client/DIRAC/Core/Utilities/DIRACScript.py", line 51, in __call__
   return self._func()  # pylint: disable=not-callable
 File "/home/owen/dirac2.esc.client/DIRAC/FrameworkSystem/scripts/dirac_admin_sysadmin_cli.py", line 31, in main
   cli.cmdloop()
 File "/home/owen/dirac2.esc.client/diracos/usr/lib64/python2.7/cmd.py", line 142, in cmdloop
   stop = self.onecmd(line)
 File "/home/owen/dirac2.esc.client/diracos/usr/lib64/python2.7/cmd.py", line 221, in onecmd
   return func(arg)
 File "/home/owen/dirac2.esc.client/DIRAC/FrameworkSystem/Client/SystemAdministratorClientCLI.py", line 268, in do_show
   gLogger.notice("DIRAC version:", result["Value"]["DIRAC"])
KeyError: 'DIRAC'
```

I discussed this with Simon Fayer who thinks this may be the result of a refactor by Chris B where the DIRAC key seems to have been removed from the returned dictionary. Simon thinks this affects all versions >= 7.3.5. 

Old:
https://github.com/DIRACGrid/DIRAC/blob/c5981031194f8d995148db09586179ce0d91bf95/src/DIRAC/Core/Utilities/Version.py#L41
New:
https://github.com/DIRACGrid/DIRAC/blob/45ddde1137f63427b587c6bcecaddbd86020a2c8/src/DIRAC/Core/Utilities/Version.py

We figured this should be logged as an issue.
Regards
Alex Owen

**Comment by fstagni** [comment]
Thanks. Fixed in https://github.com/DIRACGrid/DIRAC/pull/5622
