### ISSUE TITLE
Error in the Framework/SystemAdministrator service after update to v7.3.7

### ISSUE THREAD

**Issue by arrabito** [DIRACGrid/DIRAC#5695]
After update to v7.3 I get errors when using the Framework/SystemAdministrator service.

One example is below, when use the system admin CLI:

```
(base) ctadirac_client$ dirac-admin-sysadmin-cli --host dcta-servers.pic.es
Pinging dcta-servers.pic.es...
[dcta-servers.pic.es]> show status
[ERROR] Server error while serving getOverallStatus: string indices must be integers
```

See log:

```
2021-12-03 08:49:56 UTC Framework/SystemAdministrator DEBUG: RPC to export_getOverallStatus
2021-12-03 08:49:56 UTC Framework/SystemAdministrator ERROR: Uncaught exception when serving RPC Function getOverallStatus
Traceback (most recent call last):
  File "/opt/dirac/versions/v2.0.1-1635261390/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Core/DISET/RequestHandler.py", line 302, in __RPCCallFunction
    uReturnValue = oMethod(*args)
  File "/opt/dirac/versions/v2.0.1-1635261390/Linux-x86_64/lib/python3.9/site-packages/DIRAC/FrameworkSystem/Service/SystemAdministratorHandler.py", line 136, in export_getOverallStatus
    result = gComponentInstaller.getOverallStatus(extensionsByPriority())
  File "/opt/dirac/versions/v2.0.1-1635261390/Linux-x86_64/lib/python3.9/site-packages/DIRAC/FrameworkSystem/Client/ComponentInstaller.py", line 1250, in getOverallStatus
    result = self.getSetupComponents()
  File "/opt/dirac/versions/v2.0.1-1635261390/Linux-x86_64/lib/python3.9/site-packages/DIRAC/FrameworkSystem/Client/ComponentInstaller.py", line 1121, in getSetupComponents
    result = self.resultIndexes(self.componentTypes)
  File "/opt/dirac/versions/v2.0.1-1635261390/Linux-x86_64/lib/python3.9/site-packages/DIRAC/FrameworkSystem/Client/ComponentInstaller.py", line 226, in resultIndexes
    if not result["OK"]:
TypeError: string indices must be integers
```
And another example is an error in the log of the Framework/ComponentSupervisionAgent :

`2021-12-03 09:00:27 UTC Framework/ComponentSupervisionAgent ERROR: Failure to get Agents from system administrator client Server error while serving getOverallStatus: string indices must be integers`

Any idea?

Thank you,

Luisaework/SystemAdministrator service.

One example is below, when use the system admin CLI:

```
(base) ctadirac_client$ dirac-admin-sysadmin-cli --host dcta-servers.pic.es
Pinging dcta-servers.pic.es...
[dcta-servers.pic.es]> show status
[ERROR] Server error while serving getOverallStatus: string indices must be integers
```

See log:

```
2021-12-03 08:49:56 UTC Framework/SystemAdministrator DEBUG: RPC to export_getOverallStatus
2021-12-03 08:49:56 UTC Framework/SystemAdministrator ERROR: Uncaught exception when serving RPC Function getOverallStatus
Traceback (most recent call last):
  File "/opt/dirac/versions/v2.0.1-1635261390/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Core/DISET/RequestHandler.py", line 302, in __RPCCallFunction
    uReturnValue = oMethod(*args)
  File "/opt/dirac/versions/v2.0.1-1635261390/Linux-x86_64/lib/python3.9/site-packages/DIRAC/FrameworkSystem/Service/SystemAdministratorHandler.py", line 136, in export_getOverallStatus
    result = gComponentInstaller.getOverallStatus(extensionsByPriority())
  File "/opt/dirac/versions/v2.0.1-1635261390/Linux-x86_64/lib/python3.9/site-packages/DIRAC/FrameworkSystem/Client/ComponentInstaller.py", line 1250, in getOverallStatus
    result = self.getSetupComponents()
  File "/opt/dirac/versions/v2.0.1-1635261390/Linux-x86_64/lib/python3.9/site-packages/DIRAC/FrameworkSystem/Client/ComponentInstaller.py", line 1121, in getSetupComponents
    result = self.resultIndexes(self.componentTypes)
  File "/opt/dirac/versions/v2.0.1-1635261390/Linux-x86_64/lib/python3.9/site-packages/DIRAC/FrameworkSystem/Client/ComponentInstaller.py", line 226, in resultIndexes
    if not result["OK"]:
TypeError: string indices must be integers
```
And another example is an error in the log of the Framework/ComponentSupervisionAgent :

`2021-12-03 09:00:27 UTC Framework/ComponentSupervisionAgent ERROR: Failure to get Agents from system administrator client Server error while serving getOverallStatus: string indices must be integers`

Any idea?

Thank you,

Luisa

**Comment by fstagni** [comment]
Exactly which version of server and client are you using? We had several updates in these code in the latest patches.

**Comment by arrabito** [comment]
On the server I'm using: 7.3.7
and on the client I have: 7.3.11

but note that the Error with the ComponentSupervisionAgent involves only the server, so 7.3.7.

**Comment by fstagni** [comment]
Have you tried to update the server to the most recent version? Looks like something that was fixed already.
