### ISSUE TITLE
v7r2p39: Fix for queues with single tag not propagated from 7.3 ?

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#5826]
I just came across this error when trying to use queues that contain a single tag (at least that's the current theory). The error looked vaguely familiar and I found it in a v7r3 hackathon in August. Unfortunately I can't locate the fix (I assume it was fixed?) for it.
```
2022-01-25 12:22:40 UTC WorkloadManagement/Matcher ERROR: Uncaught exception when serving RPC Function requestJob
Traceback (most recent call last):
  File "/opt/dirac/DIRAC/Core/DISET/RequestHandler.py", line 302, in __RPCCallFunction
    uReturnValue = oMethod(*args)
  File "/opt/dirac/GridPPDIRAC/WorkloadManagementSystem/Service/MatcherHandler.py", line 45, in export_requestJob
    return super(MatcherHandler, self).export_requestJob(resourceDescription)
  File "/opt/dirac/DIRAC/WorkloadManagementSystem/Service/MatcherHandler.py", line 99, in export_requestJob
    result = matcher.selectJob(resourceDescription, credDict)
  File "/opt/dirac/DIRAC/WorkloadManagementSystem/Client/Matcher.py", line 78, in selectJob
    resourceDict = self._getResourceDict(resourceDescription, credDict)
  File "/opt/dirac/DIRAC/WorkloadManagementSystem/Client/Matcher.py", line 159, in _getResourceDict
    resourceDict = self._processResourceDescription(resourceDescription)
  File "/opt/dirac/DIRAC/WorkloadManagementSystem/Client/Matcher.py", line 215, in _processResourceDescription
    resourceDict.setdefault("Tag", []).extend(paramTags)
AttributeError: 'str' object has no attribute 'extend'
```

**Comment by marianne013** [comment]
I did some more digging. Forget about the single tag. It looks like that resourceDict["Tag"] is meant to contain a list, but if I attach a tag to a queue (e.g. I have cename/queuename/Tag GPU) in the configuration system it instead stores it as a string and then gets its knickers in a twist when it tried to extend it.

**Comment by marianne013** [comment]
I think this was fixed as part of:
https://github.com/DIRACGrid/DIRAC/pull/5354
but not backported for v7r2.
It's basically the code starting from here:
https://github.com/DIRACGrid/DIRAC/blob/835d22caa50a0bacfd792394288e222b0af8c581/src/DIRAC/WorkloadManagementSystem/Client/Matcher.py#L190
@chrisburr Is there such a thing as a backwards sweep ?

**Comment by fstagni** [comment]
Maybe https://github.com/DIRACGrid/DIRAC/pull/5827 is what you want? It just aligns with the current content of rel-v7r3

**Comment by marianne013** [comment]
Yes, that looks fine, I dumped it on my preprod server and it looks to be working.
Thanks.
