### ISSUE TITLE
[integration][critical] RuntimeError: There is no current event loop in thread 'asyncio_0'.

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#6131]
Something changed between v7r3 and v8.0 in the way tornado is ran as a new error starts showing up.
I thought it was only an artifact of a strange test (https://github.com/DIRACGrid/DIRAC/pull/6122) but I have now seen it in the logs of the LHCb certification.
So clearly something is wrong. 

```python
HTTPServerRequest(protocol='https', host='lhcbvoboxcertif00.cern.ch:8443', method='POST', uri='/WorkloadManagement/JobManager', version='HTTP/1.1', remote_ip='2001:1458:d00:a::100:7')
Traceback (most recent call last):
  File "/opt/dirac/versions/v11.0.0a2-1653977607/Linux-x86_64/lib/python3.9/site-packages/tornado/web.py", line 1571, in _execute
    result = yield result
  File "/opt/dirac/versions/v11.0.0a2-1653977607/Linux-x86_64/lib/python3.9/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/opt/dirac/versions/v11.0.0a2-1653977607/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py", line 571, in prepare
    await ioloop.run_in_executor(None, self.__prepare)
  File "/opt/dirac/versions/v11.0.0a2-1653977607/Linux-x86_64/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/dirac/versions/v11.0.0a2-1653977607/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py", line 609, in __prepare
    authorized = self._authManager.authQuery(self.__methodName, self.credDict, self.__getMethodAuthProps())
  File "/opt/dirac/versions/v11.0.0a2-1653977607/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Core/DISET/AuthManager.py", line 50, in authQuery
    requiredProperties = self.getValidPropertiesForMethod(methodQuery, defaultProperties)
  File "/opt/dirac/versions/v11.0.0a2-1653977607/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Core/DISET/AuthManager.py", line 176, in getValidPropertiesForMethod
    authProps = gConfig.getValue("%s/%s" % (self.authSection, method), [])
  File "/opt/dirac/versions/v11.0.0a2-1653977607/Linux-x86_64/lib/python3.9/site-packages/DIRAC/ConfigurationSystem/private/ConfigurationClient.py", line 123, in getValue
    retVal = self.getOption(optionPath, defaultValue)
  File "/opt/dirac/versions/v11.0.0a2-1653977607/Linux-x86_64/lib/python3.9/site-packages/DIRAC/ConfigurationSystem/private/ConfigurationClient.py", line 134, in getOption
    gRefresher.refreshConfigurationIfNeeded()
  File "/opt/dirac/versions/v11.0.0a2-1653977607/Linux-x86_64/lib/python3.9/site-packages/DIRAC/ConfigurationSystem/private/TornadoRefresher.py", line 34, in refreshConfigurationIfNeeded
    _IOLoop.current().run_in_executor(None, self._refresh)  # pylint: disable=no-member
  File "/opt/dirac/versions/v11.0.0a2-1653977607/Linux-x86_64/lib/python3.9/site-packages/tornado/ioloop.py", line 282, in current
    loop = asyncio.get_event_loop()
  File "/opt/dirac/versions/v11.0.0a2-1653977607/Linux-x86_64/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'asyncio_0'.
```

**Comment by chaen** [comment]
https://github.com/DIRACGrid/DIRAC/blob/f340453beac44bc77cfc2f3d7a1efc9debe3ef0e/src/DIRAC/WorkloadManagementSystem/Service/JobManagerHandler.py#L15

**Comment by TaykYoku** [comment]
I firmly believe that this is a common problem with non-main threads, such as https://github.com/tornadoweb/tornado/issues/2531. I believe that #6149 should fix this.

**Comment by chrisburr** [comment]
@TaykYoku Do you know if this fixes this issue or is it an educated guess?

**Comment by TaykYoku** [comment]
Hi @chrisburr 

This is a conclusion from the context of the error, I encountered this error before and enabling the **AnyThreadEventLoopPolicy** _asyncio_ policy corrected the situation, as the essence of the IIUC situation is as follows:
pice of code that applies the AnyThreadEventLoopPolicy policy is ignored when the server starts and the _asyncio_ library uses the default policy. Then at the configuration synchronization stage an an event loop is created, but not in the main thread, default asyncio policy raises a **RuntimeError** in this case.

From the asyncio [documentation](https://docs.python.org/3.6/library/asyncio-eventloops.html):

> The default policy defines context as the current thread, and manages an event loop per thread that interacts with asyncio. If the current thread doesn’t already have an event loop associated with it, the default policy’s get_event_loop () method creates one when called from the main thread, but raises RuntimeError otherwise.
