### ISSUE TITLE
CVMFS based pilots fail to start when running with integration

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#6143]
The `AgentModule` class no longer respects `/LocalSite/InstancePath` as of

https://github.com/DIRACGrid/DIRAC/commit/679707f05bf32d314601748de286fd7ed61d842a#diff-b08f851b9fd42412b4647809ce6c240334ef493ad81b1c957c5e1be1ab32da94

This then results failing pilots with tracebacks like:

```python
2022-06-07 12:56:26 UTC WorkloadManagement/JobAgent INFO: Can not connect to DB will use Monitoring/Monitoring
2022-06-07 12:56:26 UTC WorkloadManagement/JobAgent/WorkloadManagement/JobAgent INFO: Defining Inner CE from local configuration = Singularity
2022-06-07 12:56:26 UTC WorkloadManagement/JobAgent ERROR: Can't load agent WorkloadManagement/JobAgent
Traceback (most recent call last):
  File "/cvmfs/lhcbdev.cern.ch/lhcbdirac/versions/v11.0.0a2-1653981321/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Core/Base/AgentReactor.py", line 81, in loadAgentModules
    result = instanceObj.am_initialize()
  File "/cvmfs/lhcbdev.cern.ch/lhcbdirac/versions/v11.0.0a2-1653981321/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Core/Base/AgentModule.py", line 181, in am_initialize
    mkDir(self.am_getControlDirectory())
  File "/cvmfs/lhcbdev.cern.ch/lhcbdirac/versions/v11.0.0a2-1653981321/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Core/Utilities/File.py", line 32, in mkDir
    os.makedirs(path)
  File "/cvmfs/lhcbdev.cern.ch/lhcbdirac/versions/v11.0.0a2-1653981321/Linux-x86_64/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/cvmfs/lhcbdev.cern.ch/lhcbdirac/versions/v11.0.0a2-1653981321/Linux-x86_64/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/cvmfs/lhcbdev.cern.ch/lhcbdirac/versions/v11.0.0a2-1653981321/Linux-x86_64/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/cvmfs/lhcbdev.cern.ch/lhcbdirac/control'
2022-06-07 12:56:26 UTC WorkloadManagement/JobAgent ERROR: Error while loading agent module Can't load agent WorkloadManagement/JobAgent: 
 [Errno 30] Read-only file system: '/cvmfs/lhcbdev.cern.ch/lhcbdirac/control'
2022-06-07 12:56:27 UTC ERROR [LaunchAgent] Error executing the JobAgent [ERROR 2]
```

**Comment by fstagni** [comment]
This is because in the pilot we set the cfg option `/LocalSite/InstancePath` as the "working directory", which is something like /pool/condor/dir_8273/DIRAC_bs1w3dcdpilot.

I will think at a solution, with the easiest being to simply restore this cfg option.
