### ISSUE TITLE
v8.0.1 WebApp ssl issue

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#6433]
We have always run the  DIRAC WebApp directly (without a frontend). 
This fails in v8.0.1 (WebApp 5.0.0) with:
```
Traceback (most recent call last):                                                                                                                                                                                      
  File "/opt/dirac/DIRAC/src/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py", line 603, in __prepare                                                                                                           
    self.credDict = self._gatherPeerCredentials()                                                                                                                                                                       
  File "/opt/dirac/WebAppDIRAC/src/WebAppDIRAC/Lib/WebHandler.py", line 235, in _gatherPeerCredentials                                                                                                                  
    credDict = super()._gatherPeerCredentials(grants=self.__authGrant)                                                                                                                                                  
  File "/opt/dirac/DIRAC/src/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py", line 709, in _gatherPeerCredentials                                                                                              
    result = grantFunc() if callable(grantFunc) else S_ERROR("%s authentication type is not supported." % grant)                                                                                                        
  File "/opt/dirac/DIRAC/src/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py", line 735, in _authzSSL                                                                                                           
    chainAsText = derCert.as_pem().decode("ascii")                                                                                                                                                                      
AttributeError: 'dict' object has no attribute 'as_pem' 
```
Now SSL (https://docs.python.org/3/library/ssl.html) seems to have a DER_cert_to_PEM_cert function, tornado somewhat less so.
How is this meant to work ? Did it ever work ?

**Comment by chrisburr** [comment]
This is failing as it's using Python's SSL library instead configuring `tornado_m2crypto` by running:

```python
tornado.iostream.SSLIOStream.configure("tornado_m2crypto.m2iostream.M2IOStream")
```

I suspect in it's current form this has never worked as this was all changed for v8.0 as part of the OAuth stuff.

This PR seems to work in certification but I'm not certain it's actually doing the right thing: https://github.com/DIRACGrid/WebAppDIRAC/pull/699

**Comment by sfayer** [comment]
I've had a look through this and I think the headers are the only issue in this mode (other than the SSL cert issue that's fixed by the PR)... We probably just need to check the balancer setting from the config, similar to how webapp v4r3 used to do it:
```patch
diff --git a/src/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py b/src/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py
index 3edc967..82beab6 100644
--- a/src/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py
+++ b/src/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py
@@ -728,13 +728,17 @@ class BaseRequestHandler(RequestHandler):
             # If 'IOStream' object has no attribute 'get_ssl_certificate'
             derCert = None
 
+        # Boolean whether we are behind a balancer and can trust headers
+        balancer = gConfig.getValue("/WebApp/Balancer", "none") != "none"
+
         # Get client certificate as pem
         if derCert:
             chainAsText = derCert.as_pem().decode("ascii")
             # Read all certificate chain
             chainAsText += "".join([cert.as_pem().decode("ascii") for cert in self.request.get_ssl_certificate_chain()])
-        elif self.request.headers.get("X-Ssl_client_verify") == "SUCCESS" and self.request.headers.get("X-SSL-CERT"):
-            chainAsText = unquote(self.request.headers.get("X-SSL-CERT"))
+        elif balancer:
+            if self.request.headers.get("X-Ssl_client_verify") == "SUCCESS" and self.request.headers.get("X-SSL-CERT"):
+                chainAsText = unquote(self.request.headers.get("X-SSL-CERT"))
         else:
             return S_ERROR(DErrno.ECERTFIND, "Valid certificate not found.")
 ```

Any comments?

**Comment by fstagni** [comment]
I believe this can be closed now.
