### ISSUE TITLE
v8.1 (certification server) SSHBatchComputingElement/cdParameters error

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#6475]
While trying to debuh #6467 I came across this in the logs, probably needs fixing ?
```
2022-10-31 15:13:40 UTC WorkloadManagement/SiteDirectorGridpp/ComputingElementFactory ERROR: 
Traceback (most recent call last):
  File "/opt/dirac/versions/v8.1.0a3-1666850738/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Resources/Computing/ComputingElementFactory.py", line 55, in getCE
    result = computingElement.setParameters(ceDict)
  File "/opt/dirac/versions/v8.1.0a3-1666850738/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Resources/Computing/ComputingElement.py", line 238, in setParameters
    return self._reset()
  File "/opt/dirac/versions/v8.1.0a3-1666850738/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Resources/Computing/SSHBatchComputingElement.py", line 43, in _reset
    self.user = self.ceParameters["SSHUser"]
KeyError: 'SSHUser'
```

**Comment by fstagni** [comment]
I don't think it is a code issue: https://gitlab.cern.ch/ai/it-puppet-module-dirac/-/merge_requests/81
