### ISSUE TITLE
Sometimes DIRAC client fails to catch SSL timeout

### ISSUE THREAD

**Issue by hmiyake** [DIRACGrid/DIRAC#6723]
In most cases, when client fails to access to DIRAC service, it is properly caught and retry occurs as implemented in DIRAC/Core/DISET/private/BaseClient.py
```
2023-01-24 18:44:16 UTC Unknown WARN: Issue getting socket: <DIRAC.Core.DISET.private.Transports.M2SSLTransport.SSLTransport object at 0x7f37f7d3ed10> : ('dips', 'b2dcsbx1.cc.kek.jp', 9196, 'WorkloadManagement/SandboxStore') : timed out:SSLTimeoutError('timed out',)
2023-01-24 18:44:16 UTC Unknown WARN: Non-responding URL temporarily banned dips://b2dcsbx1.cc.kek.jp:9196/WorkloadManagement/SandboxStore
2023-01-24 18:44:16 UTC Unknown INFO: Retry connection : 1 to dips://b2dcsbx1.cc.kek.jp:9196/WorkloadManagement/SandboxStore
2023-01-24 18:44:16 UTC Unknown INFO: Waiting 2.000000 seconds before retry all service(s)
2023-01-24 18:44:28 UTC Unknown WARN: Issue getting socket: <DIRAC.Core.DISET.private.Transports.M2SSLTransport.SSLTransport object at 0x7f38088ab190> : ('dips', 'b2dcsbx1.cc.kek.jp', 9196, 'WorkloadManagement/SandboxStore') : timed out:SSLTimeoutError('timed out',)
2023-01-24 18:44:28 UTC Unknown WARN: Non-responding URL temporarily banned dips://b2dcsbx1.cc.kek.jp:9196/WorkloadManagement/SandboxStore
2023-01-24 18:44:28 UTC Unknown INFO: Retry connection : 2 to dips://b2dcsbx1.cc.kek.jp:9196/WorkloadManagement/SandboxStore
2023-01-24 18:44:28 UTC Unknown INFO: Waiting 2.000000 seconds before retry all service(s)
```

However, sometimes (actually in some period), it is not caught and directly exception occurs.

Here is same DIRAC component's log as above, but at different time.
```
2023-01-20 02:58:22 UTC Unknown ERROR: 
Traceback (most recent call last):
  File "/opt/dirac/pro/DIRAC/Core/DISET/private/BaseClient.py", line 482, in _connect
    retVal = transport.initAsClient()
  File "/opt/dirac/pro/DIRAC/Core/DISET/private/Transports/M2SSLTransport.py", line 145, in initAsClient
    self.oSocket.connect((host, port))
  File "/opt/dirac/pro/diracos/usr/lib64/python2.7/site-packages/M2Crypto/SSL/Connection.py", line 327, in connect
    ret = self.connect_ssl()
  File "/opt/dirac/pro/diracos/usr/lib64/python2.7/site-packages/M2Crypto/SSL/Connection.py", line 313, in connect_ssl
    return m2.ssl_connect(self.ssl, self._timeout)
SSLError: (104, 'Connection reset by peer')
2023-01-20 02:58:22 UTC Unknown WARN: Can't connect to dips://b2dcsbx1.cc.kek.jp:9196/WorkloadManagement/SandboxStore: SSLError(104, 'Connection reset by peer')
```

So I wonder if we can protect such case...
I'm trying to catch SSLError above by
```except SSL.SSLError as ex:```
where calling our service but it does not work...

Our DIRAC release is too old, v7r2 python2, so if recent or python3 DIRAC already resolved such case, it is encouraging news for us.

**Comment by chrisburr** [comment]
From the BiLD: We think this shouldn't happen in newer releases as there have been a lot of bug fixes applied to M2Crypto. If you can see this with Python 3 please let us know!
