### ISSUE TITLE
openssl 3.1.0 breaks lhcb-proxy-init

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#6925]
Investigating

```bash
Traceback (most recent call last):                                                                                                                   
  File "/home/chaen/dirac/DIRAC/src/DIRAC/ConfigurationSystem/Client/LocalConfiguration.py", line 346, in loadUserData                                                                                                                                        
    self.__initLogger(self.componentName, self.loggingSection)                                                                                       
  File "/home/chaen/dirac/DIRAC/src/DIRAC/ConfigurationSystem/Client/LocalConfiguration.py", line 313, in __initLogger                                                                                                                                        
    gLogger.initialize(componentName, logSection, forceInit=forceInit)                                                                               
  File "/home/chaen/dirac/DIRAC/src/DIRAC/FrameworkSystem/private/standardLogging/LoggingRoot.py", line 102, in initialize                                                                                                                                    
    backends = self.__getBackendsFromCFG(cfgPath)                                                                                                    
  File "/home/chaen/dirac/DIRAC/src/DIRAC/FrameworkSystem/private/standardLogging/LoggingRoot.py", line 176, in __getBackendsFromCFG                                                                                                                          
    operation = Operations()                                                                                                                         
  File "/home/chaen/dirac/DIRAC/src/DIRAC/ConfigurationSystem/Client/Helpers/Operations.py", line 104, in __init__                                                                                                                                            
    self.__discoverSettings()                                                                                                                        
  File "/home/chaen/dirac/DIRAC/src/DIRAC/ConfigurationSystem/Client/Helpers/Operations.py", line 119, in __discoverSettings                                                                                                                                  
    result = getVOfromProxyGroup()                                                                                                                   
  File "/home/chaen/dirac/DIRAC/src/DIRAC/Core/Security/ProxyInfo.py", line 201, in getVOfromProxyGroup                                                                                                                                                       
    ret = getProxyInfo(disableVOMS=True)                                                                                                             
  File "/home/chaen/dirac/DIRAC/src/DIRAC/Core/Security/ProxyInfo.py", line 50, in getProxyInfo                                                                                                                                                               
    retVal = chain.loadProxyFromFile(proxyLocation)                                                                                                  
  File "/home/chaen/dirac/DIRAC/src/DIRAC/Core/Security/m2crypto/X509Chain.py", line 321, in loadProxyFromFile                                                                                                                                                
    return self.loadProxyFromString(pemData)                                                                                                                                         
  File "/home/chaen/dirac/DIRAC/src/DIRAC/Core/Security/m2crypto/X509Chain.py", line 331, in loadProxyFromString                                                                                                                                              
    retVal = self.loadChainFromString(pemData)                                                                                                                                       
  File "/home/chaen/dirac/DIRAC/src/DIRAC/Core/Security/m2crypto/X509Chain.py", line 237, in loadChainFromString                                                                                                                                              
    self.__checkProxyness()                                                                                                                                                                                         
  File "/home/chaen/dirac/DIRAC/src/DIRAC/Core/Security/m2crypto/X509Chain.py", line 623, in __checkProxyness                                                                        
    dnMatch = self.__checkProxyDN(step, step + 1)                                                                                                                                    
  File "/home/chaen/dirac/DIRAC/src/DIRAC/Core/Security/m2crypto/X509Chain.py", line 673, in __checkProxyDN                                                                                                                                                   
    ext = self._certList[certStep].getExtension("proxyCertInfo")                                                                                                                                                    
  File "/home/chaen/dirac/DIRAC/src/DIRAC/Core/Utilities/Decorators.py", line 188, in innerFunc                                                                                                                                                               
    return meth(*args, **kwargs)                     
  File "/home/chaen/dirac/DIRAC/src/DIRAC/Core/Security/m2crypto/X509Certificate.py", line 491, in getExtension                                                                                                     
    ext = self.__certObj.get_ext(name)                                                                                                                                                                              
  File "/home/chaen/miniconda3/envs/diracprod/lib/python3.9/site-packages/M2Crypto/X509.py", line 732, in get_ext                                                                                                   
    if m2x509_extension_get_name(ext_ptr) == name:                                                                                                                                                                  
M2Crypto.X509.X509Error: Unknown error in function x509_extension_get_name.                                                                                                                                                                                   
Generating proxy...  
```

**Comment by chaen** [comment]
The problem can also be seen in the DIRACOS2 nightlies
https://github.com/DIRACGrid/DIRACOS2/actions/runs/4464184360/jobs/7840170455

The problem happens in 
https://gitlab.com/m2crypto/m2crypto/-/blob/master/src/SWIG/_x509.i#L707-716

I've added printout in the method, and look at the outcome when doing `lhcb-proxy-init`


<details>
  <summary>Openssl 1.1.1</summary>

```
nid 83  ext_name_str keyUsage!!
nid 663  ext_name_str proxyCertInfo!!
nid 83  ext_name_str keyUsage!!
nid 85  ext_name_str subjectAltName!!
nid 83  ext_name_str keyUsage!!
nid 663  ext_name_str proxyCertInfo!!
nid 0  ext_name_str UNDEF!!
nid 83  ext_name_str keyUsage!!
nid 87  ext_name_str basicConstraints!!
nid 90  ext_name_str authorityKeyIdentifier!!
nid 663  ext_name_str proxyCertInfo!!
nid 83  ext_name_str keyUsage!!
nid 663  ext_name_str proxyCertInfo!!
nid 0  ext_name_str UNDEF!!
nid 83  ext_name_str keyUsage!!
nid 87  ext_name_str basicConstraints!!
nid 90  ext_name_str authorityKeyIdentifier!!
nid 663  ext_name_str proxyCertInfo!!
nid 83  ext_name_str keyUsage!!
nid 663  ext_name_str proxyCertInfo!!
nid 83  ext_name_str keyUsage!!
nid 85  ext_name_str subjectAltName!!
nid 0  ext_name_str UNDEF!!
nid 83  ext_name_str keyUsage!!
nid 87  ext_name_str basicConstraints!!
nid 90  ext_name_str authorityKeyIdentifier!!
nid 663  ext_name_str proxyCertInfo!!
nid 83  ext_name_str keyUsage!!
nid 663  ext_name_str proxyCertInfo!!
nid 83  ext_name_str keyUsage!!
nid 85  ext_name_str subjectAltName!!
nid 0  ext_name_str UNDEF!!
nid 83  ext_name_str keyUsage!!
nid 87  ext_name_str basicConstraints!!
nid 90  ext_name_str authorityKeyIdentifier!!
nid 663  ext_name_str proxyCertInfo!!
nid 83  ext_name_str keyUsage!!
nid 663  ext_name_str proxyCertInfo!!
```
</details>


<details>
  <summary>Openssl 3.1.0</summary>

```
 nid 83  ext_name_str keyUsage!!
 nid 663  ext_name_str proxyCertInfo!!
 nid 83  ext_name_str keyUsage!!
 nid 85  ext_name_str subjectAltName!!
 nid 83  ext_name_str keyUsage!!
 nid 663  ext_name_str proxyCertInfo!!
 nid 0  ext_name_str (null)!!
Traceback (most recent call last):
  File "/home/chaen/miniconda3/envs/diracprod/bin/dirac-proxy-init", line 8, in <module>
    sys.exit(main())
  File "/home/chaen/dirac/DIRAC/src/DIRAC/Core/Base/Script.py", line 74, in __call__
    return entrypointFunc._func()
  File "/home/chaen/dirac/DIRAC/src/DIRAC/FrameworkSystem/scripts/dirac_proxy_init.py", line 256, in main
    resultDoTheMagic = pI.doTheMagic()
  File "/home/chaen/dirac/DIRAC/src/DIRAC/FrameworkSystem/scripts/dirac_proxy_init.py", line 222, in doTheMagic
    resultProxyWithVOMS = pI.addVOMSExtIfNeeded()
  File "/home/chaen/dirac/DIRAC/src/DIRAC/FrameworkSystem/scripts/dirac_proxy_init.py", line 98, in addVOMSExtIfNeeded
    resultVomsAttributes = VOMS.VOMS().setVOMSAttributes(
  File "/home/chaen/dirac/DIRAC/src/DIRAC/Core/Security/VOMS.py", line 308, in setVOMSAttributes
    retVal = newChain.loadProxyFromFile(newProxyLocation)
  File "/home/chaen/dirac/DIRAC/src/DIRAC/Core/Security/m2crypto/X509Chain.py", line 321, in loadProxyFromFile
    return self.loadProxyFromString(pemData)
  File "/home/chaen/dirac/DIRAC/src/DIRAC/Core/Security/m2crypto/X509Chain.py", line 331, in loadProxyFromString
    retVal = self.loadChainFromString(pemData)
  File "/home/chaen/dirac/DIRAC/src/DIRAC/Core/Security/m2crypto/X509Chain.py", line 237, in loadChainFromString
    self.__checkProxyness()
  File "/home/chaen/dirac/DIRAC/src/DIRAC/Core/Security/m2crypto/X509Chain.py", line 623, in __checkProxyness
    dnMatch = self.__checkProxyDN(step, step + 1)
  File "/home/chaen/dirac/DIRAC/src/DIRAC/Core/Security/m2crypto/X509Chain.py", line 673, in __checkProxyDN
    ext = self._certList[certStep].getExtension("proxyCertInfo")
  File "/home/chaen/dirac/DIRAC/src/DIRAC/Core/Utilities/Decorators.py", line 188, in innerFunc
    return meth(*args, **kwargs)
  File "/home/chaen/dirac/DIRAC/src/DIRAC/Core/Security/m2crypto/X509Certificate.py", line 491, in getExtension
    ext = self.__certObj.get_ext(name)
  File "/home/chaen/miniconda3/conda-bld/debug_1679365595583/work/src/M2Crypto/X509.py", line 732, in get_ext
    if m2x509_extension_get_name(ext_ptr) == name:
M2Crypto.X509.X509Error: Unknown error in function x509_extension_get_name.

```
</details>

The problem seems to lie in `OBJ_nid2sn`

https://github.com/openssl/openssl/blob/6ec3d3125f76aa9f11c133333f868c42b9b585c4/crypto/objects/obj_dat.c#L324-L329

With `openssl 1.1.1`, an `NID` of 0 would return `UNDEF`, while it returns `null` for `openssl 3.1.0`

I am trying to dig a bit to understand, but I have limited debugging capabilities with openssl at the moment :-D

**Comment by chaen** [comment]
Note that it seems we can live with catching more exceptions here https://github.com/DIRACGrid/DIRAC/blob/eba60613502de6e35e0ef4a5c1b59c3eb6fa4da5/src/DIRAC/Core/Security/m2crypto/X509Certificate.py#L492

But I still want to understand...

**Comment by chaen** [comment]
OK, I blame this change:

https://github.com/openssl/openssl/commit/196c57ee6a956169aadbd760c13110671773f371#diff-9c1ebb22ae4d666ae0cdda6014f30ec0c2e5090fc8e549200988274a8e550904L221-L237

I'll open an issue against openssl as soon as I manage to compile a stupid test program in conda, grrrr

**Comment by chaen** [comment]
OK, I blame this change:

https://github.com/openssl/openssl/commit/196c57ee6a956169aadbd760c13110671773f371#diff-9c1ebb22ae4d666ae0cdda6014f30ec0c2e5090fc8e549200988274a8e550904L221-L237

I'll open an issue against openssl as soon as I manage to compile a stupid test program in conda, grrrr

**Comment by chaen** [comment]
https://github.com/openssl/openssl/issues/20555

**Comment by chaen** [comment]
There's already a PR in openssl, so just have to be a bit patient and not make a `DIRACOS2` release right now :-D
