### ISSUE TITLE
Newly installed clients cant create proxy: "M2Crypto.BIO.BIOError:illegal zero content"

### ISSUE THREAD

**Issue by IgorPelevanyuk** [DIRACGrid/DIRAC#7038]
Hello, recently I tried to install DIRAC client on ubuntu 20.04 in the same way as i did before. But after client installation I cannot create proxy. I see error:

```
Added VOMS attribute /mpd.nica.jinr
Uploading proxy..
Traceback (most recent call last):
  File "/home/ipelevan/Downloads/dirac/diracos/bin/dirac-proxy-init", line 8, in <module>
    sys.exit(main())
  File "/home/ipelevan/Downloads/dirac/diracos/lib/python3.9/site-packages/DIRAC/Core/Utilities/DIRACScript.py", line 80, in __call__
    return entrypointFunc._func()
  File "/home/ipelevan/Downloads/dirac/diracos/lib/python3.9/site-packages/DIRAC/FrameworkSystem/scripts/dirac_proxy_init.py", line 269, in main
    resultDoTheMagic = pI.doTheMagic()
  File "/home/ipelevan/Downloads/dirac/diracos/lib/python3.9/site-packages/DIRAC/FrameworkSystem/scripts/dirac_proxy_init.py", line 250, in doTheMagic
    resultProxyUpload = pI.uploadProxy()
  File "/home/ipelevan/Downloads/dirac/diracos/lib/python3.9/site-packages/DIRAC/FrameworkSystem/scripts/dirac_proxy_init.py", line 162, in uploadProxy
    resultProxyUpload = ProxyUpload.uploadProxy(upParams)
  File "/home/ipelevan/Downloads/dirac/diracos/lib/python3.9/site-packages/DIRAC/FrameworkSystem/Client/ProxyUpload.py", line 164, in uploadProxy
    return gProxyManager.uploadProxy(proxy=chain, restrictLifeTime=restrictLifeTime, rfcIfPossible=params.rfcIfPossible)
  File "/home/ipelevan/Downloads/dirac/diracos/lib/python3.9/site-packages/DIRAC/FrameworkSystem/Client/ProxyManagerClient.py", line 217, in uploadProxy
    retVal = chain.generateChainFromRequestString(reqDict["request"], lifetime=chainLifeTime, rfc=rfcIfPossible)
  File "/home/ipelevan/Downloads/dirac/diracos/lib/python3.9/site-packages/DIRAC/Core/Utilities/Decorators.py", line 191, in innerFunc
    return meth(*args, **kwargs)
  File "/home/ipelevan/Downloads/dirac/diracos/lib/python3.9/site-packages/DIRAC/Core/Utilities/Decorators.py", line 191, in innerFunc
    return meth(*args, **kwargs)
  File "/home/ipelevan/Downloads/dirac/diracos/lib/python3.9/site-packages/DIRAC/Core/Security/m2crypto/X509Chain.py", line 834, in generateChainFromRequestString
    return self.generateProxyToString(lifetime, diracGroup, 1024, limited, req.get_pubkey())
  File "/home/ipelevan/Downloads/dirac/diracos/lib/python3.9/site-packages/DIRAC/Core/Utilities/Decorators.py", line 191, in innerFunc
    return meth(*args, **kwargs)
  File "/home/ipelevan/Downloads/dirac/diracos/lib/python3.9/site-packages/DIRAC/Core/Utilities/Decorators.py", line 191, in innerFunc
    return meth(*args, **kwargs)
  File "/home/ipelevan/Downloads/dirac/diracos/lib/python3.9/site-packages/DIRAC/Core/Security/m2crypto/X509Chain.py", line 476, in generateProxyToString
    proxyKey.as_pem(cipher=None, callback=M2Crypto.util.no_passphrase_callback),
  File "/home/ipelevan/Downloads/dirac/diracos/lib/python3.9/site-packages/M2Crypto/EVP.py", line 449, in as_pem
    return bio.read_all()
  File "/home/ipelevan/Downloads/dirac/diracos/lib/python3.9/site-packages/M2Crypto/BIO.py", line 204, in read
    return m2.bio_read(self.bio, m2.bio_ctrl_pending(self.bio))
M2Crypto.BIO.BIOError: illegal zero content
```

How I installing DIRAC: 
```
mkdir dirac
cd dirac
curl -LO https://github.com/DIRACGrid/DIRACOS2/releases/latest/download/DIRACOS-Linux-$(uname -m).sh
bash DIRACOS-Linux-x86_64.sh
rm -rf DIRACOS-Linux-x86_64.sh
source diracos/diracosrc
pip install DIRAC==7.3.29
dirac-proxy-init -x
dirac-configure -S JINR-Production -C 'dips://dirac-services.jinr.ru:9135/Configuration/Server'
pip install COMDIRAC
dirac-proxy-init -g mpd_user -M
```

Now I have two clinets on the same machine and old is working and new client gives me an error.

**Comment by andresailer** [comment]
I fixed that error yesterday for iLCDirac. You need at least DIRAC 7.3.35. I think this is the openssl 3 compatibility mentioned in those release notes.

**Comment by IgorPelevanyuk** [comment]
Thank you, Andre! 
I have installed newer version of DIRAC client and proxy was created. Hope that there is no problems between interaction of v7r3p29 server and v7r3p35 client.
