### ISSUE TITLE
Library psutil returns error sometimes

### ISSUE THREAD

**Issue by IgorPelevanyuk** [DIRACGrid/DIRAC#7109]
Hello dear colleagues, 

We are observing issue on some of our resources related to the use of psutil:
```
2023-05-03 07:06:06 UTC None/JobWrapper[2948947] INFO: Job Wrapper is starting execution phase for job 2948947
Job raised exception during execution phase
Traceback (most recent call last):
  File "/zfs/tmp/dirac/DIRAC_YCzSdFpilot/job/Wrapper/Wrapper_2948947", line 179, in execute
    result = job.execute()
  File "/zfs/tmp/dirac/DIRAC_YCzSdFpilot/diracos/lib/python3.9/site-packages/DIRAC/WorkloadManagementSystem/JobWrapper/JobWrapper.py", line 435, in execute
    watchdog.calibrate()
  File "/zfs/tmp/dirac/DIRAC_YCzSdFpilot/diracos/lib/python3.9/site-packages/DIRAC/WorkloadManagementSystem/JobWrapper/Watchdog.py", line 791, in calibrate
    result = self.getNodeInformation()
  File "/zfs/tmp/dirac/DIRAC_YCzSdFpilot/diracos/lib/python3.9/site-packages/DIRAC/WorkloadManagementSystem/JobWrapper/Watchdog.py", line 973, in getNodeInformation
    result["CPU(MHz)"] = psutil.cpu_freq()[0]
  File "/zfs/tmp/dirac/DIRAC_YCzSdFpilot/diracos/lib/python3.9/site-packages/psutil/__init__.py", line 1864, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/zfs/tmp/dirac/DIRAC_YCzSdFpilot/diracos/lib/python3.9/site-packages/psutil/_pslinux.py", line 745, in cpu_freq
    max_ = int(bcat(pjoin(path, "scaling_max_freq"))) / 1000
  File "/zfs/tmp/dirac/DIRAC_YCzSdFpilot/diracos/lib/python3.9/site-packages/psutil/_common.py", line 776, in bcat
    return cat(fname, fallback=fallback, _open=open_binary)
  File "/zfs/tmp/dirac/DIRAC_YCzSdFpilot/diracos/lib/python3.9/site-packages/psutil/_common.py", line 765, in cat
    return f.read()
OSError: [Errno 16] Device or resource busy
```

Issue here is related to the fact that the kernel file is not always accessible. This problem appears when there are many processes running. CPU frequency information exists at the following path: /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq

So, is that possible to wrap:
```
packages/DIRAC/WorkloadManagementSystem/JobWrapper/Watchdog.py", line 973, in getNodeInformation
    result["CPU(MHz)"] = psutil.cpu_freq()[0]
```
in try except clause? 

Does the MHz information is crucial or useful for DIRAC?

**Comment by IgorPelevanyuk** [comment]
I found that this line was removed in version 8. 
result["CPU(MHz)"] = psutil.cpu_freq()[0]

So, my question is the following. Can I apply that change for version v7r3p29? So I would not need to update right now. And I think that the issue may be closed.

**Comment by chaen** [comment]
Yes you can: https://github.com/DIRACGrid/DIRAC/pull/6336

**Comment by IgorPelevanyuk** [comment]
But, changing that locally does not affect pilots running on remote resources. Or is it?

**Comment by chaen** [comment]
Sorry, what I meant was: feel free to back port it to v7r3 if you like :-)

**Comment by IgorPelevanyuk** [comment]
Thanks for coment) I also have tried to make an opposite, use newer version of pilot 8.0.23 with v7r0p29 version of DIRAC servers. It worked!
