### ISSUE TITLE
[8.0.23] Uncaught exception in Tornado

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#7127]
This is on our preprod server. We see the following exception showing up, without a hint what is going on:
```
ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado/iostream.py", line 711, in _handle_events
    self._handle_read()
  File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado/iostream.py", line 1616, in _handle_read
    self._do_ssl_handshake()
  File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado_m2crypto/m2iostream.py", line 175, in _do_ssl_handshake
    res = self.socket.accept_ssl()
  File "/opt/dirac/diracos/lib/python3.9/site-packages/M2Crypto/SSL/Connection.py", line 275, in accept_ssl
    return m2.ssl_accept(self.ssl, self._timeout)
M2Crypto.SSL.SSLError: http request
ERROR:asyncio:Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "/opt/dirac/diracos/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado/iostream.py", line 711, in _handle_events
    self._handle_read()
  File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado/iostream.py", line 1616, in _handle_read
    self._do_ssl_handshake()
  File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado_m2crypto/m2iostream.py", line 175, in _do_ssl_handshake
    res = self.socket.accept_ssl()
  File "/opt/dirac/diracos/lib/python3.9/site-packages/M2Crypto/SSL/Connection.py", line 275, in accept_ssl
    return m2.ssl_accept(self.ssl, self._timeout)
M2Crypto.SSL.SSLError: http request
```
Any idea ? We haven't managed to tie it to any particular action.

**Comment by fstagni** [comment]
8.0 or 8.1? And why is it using the not-latest DIRACOS?

**Comment by marianne013** [comment]
8.0 and we don't always update the preprod server every time. If you think it's fixed in the latest and greatest version I can update it.

**Comment by marianne013** [comment]
It's now on the latest and greatest version.

**Comment by marianne013** [comment]
It's broken.

**Comment by fstagni** [comment]
This unfortunately tells me nothing about what could be wrong. Any change of getting more details?

**Comment by marianne013** [comment]
I've now installed 2.33 as this is what we run on the production server, so I know it works.
The error I see for the latest version is that on trying to start up the services I get:
```
critical libmamba Unknown shell type. Aborting.
error    libmamba Please provide a shell type.
    Run with --help for more information.
```
over and over again.

I think Chris' fix for the prompt issue might have gone wrong.

**Comment by fstagni** [comment]
We are running in LHCb production 2.35:

```
$ more /opt/dirac/pro/Linux-x86_64/.diracos_version 
DIRACOS2 2.35
```

and this works OK.

**Comment by marianne013** [comment]
Good for you, doesn't help me though.

**Comment by marianne013** [comment]
We are now on diracos 2.33 and 8.0.25 on the pre-prod server. I'll see if that error recurres, otherwise I'll close the issue as "version mismatch".

**Comment by marianne013** [comment]
Unless young @sfayer owns up to something there were a long bunch of uncaught exceptions this morning (diracos2.33 & 8.0.25):
```
2023-07-27 09:39:31 UTC Tornado/Tornado/MessageBroker DEBUG: [trid 2a0c:5bc0:c8:2:216:3eff:fe7f:1bc:59834->2a0c:5bc0:c8:2:216:3eff:fe7f:1bc:9175] Received data: {'OK': True, 'Va\
lue': None, 'keepAlive': True}
ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado/iostream.py", line 711, in _handle_events
    self._handle_read()
  File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado/iostream.py", line 1616, in _handle_read
    self._do_ssl_handshake()
  File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado_m2crypto/m2iostream.py", line 175, in _do_ssl_handshake
    res = self.socket.accept_ssl()
  File "/opt/dirac/diracos/lib/python3.9/site-packages/M2Crypto/SSL/Connection.py", line 275, in accept_ssl
    return m2.ssl_accept(self.ssl, self._timeout)
M2Crypto.SSL.SSLError: http request
ERROR:asyncio:Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "/opt/dirac/diracos/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado/iostream.py", line 711, in _handle_events
    self._handle_read()
  File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado/iostream.py", line 1616, in _handle_read
    self._do_ssl_handshake()
  File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado_m2crypto/m2iostream.py", line 175, in _do_ssl_handshake
    res = self.socket.accept_ssl()
  File "/opt/dirac/diracos/lib/python3.9/site-packages/M2Crypto/SSL/Connection.py", line 275, in accept_ssl
    return m2.ssl_accept(self.ssl, self._timeout)
M2Crypto.SSL.SSLError: http request
ARN:tornado.access:404 GET / (183.136.225.5) 2.58ms
WARN:tornado.access:404 GET /static/core/img/icons/system/favicon.ico (183.136.225.5) 2.31ms
WARN:tornado.access:404 GET /static/core/img/icons/system/favicon.ico (183.136.225.5) 2.11ms
WARN:tornado.access:404 GET / (183.136.225.5) 2.77ms
WARN:tornado.access:404 GET /favicon.ico (183.136.225.5) 2.28ms
WARN:tornado.access:404 GET /robots.txt (183.136.225.5) 2.07ms
ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado/iostream.py", line 711, in _handle_events
    self._handle_read()
  File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado/iostream.py", line 1616, in _handle_read
    self._do_ssl_handshake()
  File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado_m2crypto/m2iostream.py", line 175, in _do_ssl_handshake
    res = self.socket.accept_ssl()
  File "/opt/dirac/diracos/lib/python3.9/site-packages/M2Crypto/SSL/Connection.py", line 275, in accept_ssl
    return m2.ssl_accept(self.ssl, self._timeout)
M2Crypto.SSL.SSLError: (104, 'Connection reset by peer')
ERROR:asyncio:Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "/opt/dirac/diracos/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado/iostream.py", line 711, in _handle_events
    self._handle_read()
  File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado/iostream.py", line 1616, in _handle_read
    self._do_ssl_handshake()
  File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado_m2crypto/m2iostream.py", line 175, in _do_ssl_handshake
    res = self.socket.accept_ssl()
  File "/opt/dirac/diracos/lib/python3.9/site-packages/M2Crypto/SSL/Connection.py", line 275, in accept_ssl
    return m2.ssl_accept(self.ssl, self._timeout)
```
and more....

**Comment by marianne013** [comment]
I tried (again) to install the latest version of diracos, but I get the aforementioned
```
critical libmamba Unknown shell type. Aborting.
error    libmamba Please provide a shell type.
    Run with --help for more information.
```
error when trying to start up DIRAC.
Possibly one for @chrisburr

**Comment by chaen** [comment]
> We are running in LHCb production 2.35:
> 
> ```
> $ more /opt/dirac/pro/Linux-x86_64/.diracos_version 
> DIRACOS2 2.35
> ```
> 
> and this works OK.

actually I've spotted the same error as @marianne013 a few days ago, but it seems harmless :man_shrugging:

**Comment by marianne013** [comment]
> > We are running in LHCb production 2.35:
> > ```
> > $ more /opt/dirac/pro/Linux-x86_64/.diracos_version 
> > DIRACOS2 2.35
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and this works OK.
> 
> actually I've spotted the same error as @marianne013 a few days ago, but it seems harmless man_shrugging

I like my terminals to be usable after starting DIRAC and not being flooded with failure messages ;-)

**Comment by marianne013** [comment]
@chaen, @chrisburr Before I go back to testing this, was this ("critical libmamba Unknown shell type. Aborting.") fixed in diracos ?

**Comment by marianne013** [comment]
Not in 2.36 apparently, grrr

**Comment by fstagni** [comment]
IIUC this is fixed now. Please re-open if not the case.
