### ISSUE TITLE
Missing setup in Framework/ComponentSupervisionAgent

### ISSUE THREAD

**Issue by aldbr** [DIRACGrid/DIRAC#7235]
Don't know if it is a bug or just a problem of configuration. In LHCb, `Framework/ComponentSupervisionAgent` does not have any `Setup` parameter: 

https://github.com/DIRACGrid/DIRAC/blob/fdddd04e1d4b283c6d4dae19283c62b72b50bbc2/src/DIRAC/FrameworkSystem/Agent/ComponentSupervisionAgent.py#L124

```bash
2023-10-11 07:03:17 UTC Framework/ComponentSupervisionAgent/Framework/ComponentSupervisionAgent ERROR: Agent exception while calling method beginExecution
Traceback (most recent call last):
  File "/opt/dirac/versions/v11.0.21-1696937819/Linux-x86_64/lib/python3.11/site-packages/DIRAC/Core/Base/AgentModule.py", line 310, in am_secureCall
    result = functor(*args)
             ^^^^^^^^^^^^^^
  File "/opt/dirac/versions/v11.0.21-1696937819/Linux-x86_64/lib/python3.11/site-packages/DIRAC/FrameworkSystem/Agent/ComponentSupervisionAgent.py", line 139, in beginExecution
    res = self.getRunningInstances(instanceType="Agents")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/dirac/versions/v11.0.21-1696937819/Linux-x86_64/lib/python3.11/site-packages/DIRAC/FrameworkSystem/Agent/ComponentSupervisionAgent.py", line 212, in getRunningInstances
    runningComponents[fullName][option] = self._getComponentOption(
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/dirac/versions/v11.0.21-1696937819/Linux-x86_64/lib/python3.11/site-packages/DIRAC/FrameworkSystem/Agent/ComponentSupervisionAgent.py", line 230, in _getComponentOption
    componentPath = PathFinder.getComponentSection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/dirac/versions/v11.0.21-1696937819/Linux-x86_64/lib/python3.11/site-packages/DIRAC/ConfigurationSystem/Client/PathFinder.py", line 87, in getComponentSection
    return Path.cfgPath(getSystemSection(system, setup=setup), componentCategory, component)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/dirac/versions/v11.0.21-1696937819/Linux-x86_64/lib/python3.11/site-packages/DIRAC/ConfigurationSystem/Client/PathFinder.py", line 63, in getSystemSection
    instance or getSystemInstance(system, setup=setup),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/dirac/versions/v11.0.21-1696937819/Linux-x86_64/lib/python3.11/site-packages/DIRAC/ConfigurationSystem/Client/PathFinder.py", line 46, in getSystemInstance
    raise RuntimeError(f"Option {optionPath} is not defined")
RuntimeError: Option /DIRAC/Setups/DIRAC-Production/Framework is not defined
```

**Comment by andresailer** [comment]
It is a problem of your configuration?
https://github.com/DIRACGrid/DIRAC/blob/fdddd04e1d4b283c6d4dae19283c62b72b50bbc2/src/DIRAC/FrameworkSystem/ConfigTemplate.cfg#L212

**Comment by aldbr** [comment]
It does not seem to be the case.
The `Setup` is correctly set in `/opt/dirac/etc/dirac.cfg`, I can get it using `gConfig.getValue("DIRAC/Setup")`.

Update: sorry, I looked too fast, you are right.

**Comment by aldbr** [comment]
I guess this parameter is needed because you can have multiple setups in `v8.0` and you need to tell to the `ComponentSupervisionAgent` which one you want to supervise. 
Can't it be done based on the setup locally defined in the local `dirac.cfg` where the agent is installed?

**Comment by andresailer** [comment]
I think it was needed before these changes https://github.com/DIRACGrid/DIRAC/commit/27a3071b5095c1f2a09586639c6b77ac1f87cf72
So yes, we can take it from gConfig now.
