### ISSUE TITLE
show status broken when using dirac-admin-sysadmin-cli

### ISSUE THREAD

**Issue by cserf** [DIRACGrid/DIRAC#7246]
After updating from 7.3 to 8.0, we have the following error :

```python
dirac-admin-sysadmin-cli -H $( hostname -f ) -c y 
Using port '3306' as MySQL port
Using 'root' as root MySQL user
NoSQL SSL choice not found
Pinging xxx...
[xxx]> show status
Traceback (most recent call last):
  File "/opt/dirac/versions/v5.9.0.dev1-1697211049/Linux-x86_64/bin/dirac-admin-sysadmin-cli", line 8, in <module>
    sys.exit(main())
  File "/opt/dirac/versions/v5.9.0.dev1-1697211049/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Core/Base/Script.py", line 74, in __call__
    return entrypointFunc._func()
  File "/opt/dirac/versions/v5.9.0.dev1-1697211049/Linux-x86_64/lib/python3.9/site-packages/DIRAC/FrameworkSystem/scripts/dirac_admin_sysadmin_cli.py", line 25, in main
    cli.cmdloop()
  File "/opt/dirac/versions/v5.9.0.dev1-1697211049/Linux-x86_64/lib/python3.9/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/opt/dirac/versions/v5.9.0.dev1-1697211049/Linux-x86_64/lib/python3.9/cmd.py", line 217, in onecmd
    return func(arg)
  File "/opt/dirac/versions/v5.9.0.dev1-1697211049/Linux-x86_64/lib/python3.9/site-packages/DIRAC/FrameworkSystem/Client/SystemAdministratorClientCLI.py", line 201, in do_show
    module = str(rDict[compType][system][component]["DIRACModule"])
KeyError: 'DIRACModule'
```

**Comment by chaen** [comment]
You do have the fix ready right ?

**Comment by fstagni** [comment]
To which version of DIRAC v8 did you update to? the latest one? (I have a feeling of deja-vu...)

**Comment by cserf** [comment]
Checking code :
```
2520cb3209 src/DIRAC/FrameworkSystem/Client/SystemAdministratorClientCLI.py (Federico Stagni       2023-03-08 16:57:07 +0100  201)                                 module = str(rDict[compType][system][component]["DIRACModule"])
```
This line was modified a few months ago https://github.com/DIRACGrid/DIRAC/pull/6892/files
