### ISSUE TITLE
"M2Crypto.SSL.SSLError: ee key too small" error during proxy generation

### ISSUE THREAD

**Issue by IgorPelevanyuk** [DIRACGrid/DIRAC#7427]
May be reated to #6269

I have updated host certificate for DIRAC and tried to install DIRAC client 7.3.35
But after dirac-proxy-init -x (which executed successfully) I could not make dirac-configure due to error:
```
Traceback (most recent call last):
  File "/home/ipelevan/dirac/diracos/lib/python3.11/site-packages/DIRAC/Core/DISET/private/BaseClient.py", line 479, in _connect
    transport = gProtocolDict[self.__URLTuple[0]]["transport"](self.__URLTuple[1:3], **self.kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ipelevan/dirac/diracos/lib/python3.11/site-packages/DIRAC/Core/DISET/private/Transports/M2SSLTransport.py", line 94, in __init__
    self.__ctx = getM2SSLContext(**kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ipelevan/dirac/diracos/lib/python3.11/site-packages/DIRAC/Core/DISET/private/Transports/SSL/M2Utils.py", line 111, in getM2SSLContext
    __loadM2SSLCTXProxy(ctx, proxyPath=kwargs.get("proxyLocation", None))
  File "/home/ipelevan/dirac/diracos/lib/python3.11/site-packages/DIRAC/Core/DISET/private/Transports/SSL/M2Utils.py", line 52, in __loadM2SSLCTXProxy
    ctx.load_cert_chain(proxyPath, proxyPath, callback=lambda: "")
  File "/home/ipelevan/dirac/diracos/lib/python3.11/site-packages/M2Crypto/SSL/Context.py", line 118, in load_cert_chain
    m2.ssl_ctx_use_cert_chain(self.ctx, certchainfile)
M2Crypto.SSL.SSLError: ee key too small
Could not sync dir Cannot get URL for Framework/BundleDelivery in setup JINR-Production: RuntimeError('Option /DIRAC/Setups/JINR-Production/Framework is not defined')
```

I increased sthrength of the proxy by `dirac-proxy-init -x --strength 2048` and after that dirac-configure finished successfuly.

And not it is not possible to generate proxy without `--strength 2048`
```
$ dirac-proxy-init -g bmn_user -M
Generating proxy...
Enter Certificate password: ******************

Traceback (most recent call last):
  File "/home/ipelevan/dirac/diracos/lib/python3.11/site-packages/DIRAC/Core/DISET/private/BaseClient.py", line 479, in _connect
    transport = gProtocolDict[self.__URLTuple[0]]["transport"](self.__URLTuple[1:3], **self.kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ipelevan/dirac/diracos/lib/python3.11/site-packages/DIRAC/Core/DISET/private/Transports/M2SSLTransport.py", line 94, in __init__
    self.__ctx = getM2SSLContext(**kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ipelevan/dirac/diracos/lib/python3.11/site-packages/DIRAC/Core/DISET/private/Transports/SSL/M2Utils.py", line 111, in getM2SSLContext
    __loadM2SSLCTXProxy(ctx, proxyPath=kwargs.get("proxyLocation", None))
  File "/home/ipelevan/dirac/diracos/lib/python3.11/site-packages/DIRAC/Core/DISET/private/Transports/SSL/M2Utils.py", line 52, in __loadM2SSLCTXProxy
    ctx.load_cert_chain(proxyPath, proxyPath, callback=lambda: "")
  File "/home/ipelevan/dirac/diracos/lib/python3.11/site-packages/M2Crypto/SSL/Context.py", line 118, in load_cert_chain
    m2.ssl_ctx_use_cert_chain(self.ctx, certchainfile)
M2Crypto.SSL.SSLError: ee key too small
```

With  `--strength 2048` option proxy generates correctly. 
It is strange, because both keys (user and host) are 2048 bit RSA.

**Comment by IgorPelevanyuk** [comment]
Pilots started to fail. 

I found that DIRAC ProxyGeneration by default creates proxies with 1024 strength. So, I tried manually  change the default value in /dirac/diracos/lib/python3.11/site-packages/DIRAC/FrameworkSystem/Client/ProxyGeneration.py

But that did not worked out, and pilots are still failing. Pilot Version 8.0.23.

**Comment by chrisburr** [comment]
> I have updated host certificate for DIRAC and tried to install DIRAC client 7.3.35

As we discussed in the last BiLD, v7r3 is no longer supported.

You probably need to delete the proxy from the proxy manager and upload a new one using a v8.0 client (as proxies aren't overwritten).

**Comment by IgorPelevanyuk** [comment]
@chrisburr Thank you for the information. 

I have:
1. Updated DIRAC server to be 8.0.36. 
2. Removed my personal proxy using WebApp.ProxyManager
3. Installed new client of 8.0.36
4. Configured pilot to use version 8.0.36
5. Created proxy with new client. 
6. Submitted jobs.

Now it works!
