### ISSUE TITLE
Client depends on opensearchpy

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#7567]
I think this probably shouldn't be a strict dependnecy in the client. If it does need to be it should be fixed in the `setup.cfg`.

```bash
$ dsub --help
Traceback (most recent call last):
  File "/Users/cburr/mambaforge/conda-bld/dirac-grid_1712762382100/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/DIRAC/Core/Utilities/ElasticSearchDB.py", line 16, in <module>
    from opensearchpy import OpenSearch as Elasticsearch
ModuleNotFoundError: No module named 'opensearchpy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cburr/mambaforge/conda-bld/dirac-grid_1712762382100/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/dsub", line 6, in <module>
    from DIRAC.Interfaces.scripts.dsub import main
  File "/Users/cburr/mambaforge/conda-bld/dirac-grid_1712762382100/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/DIRAC/Interfaces/scripts/dsub.py", line 17, in <module>
    from DIRAC.Interfaces.API.Dirac import Dirac
  File "/Users/cburr/mambaforge/conda-bld/dirac-grid_1712762382100/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/DIRAC/Interfaces/API/Dirac.py", line 44, in <module>
    from DIRAC.DataManagementSystem.Client.DataManager import DataManager
  File "/Users/cburr/mambaforge/conda-bld/dirac-grid_1712762382100/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/DIRAC/DataManagementSystem/Client/DataManager.py", line 28, in <module>
    from DIRAC.MonitoringSystem.Client.DataOperationSender import DataOperationSender
  File "/Users/cburr/mambaforge/conda-bld/dirac-grid_1712762382100/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/DIRAC/MonitoringSystem/Client/DataOperationSender.py", line 16, in <module>
    from DIRAC.MonitoringSystem.Client.MonitoringReporter import MonitoringReporter
  File "/Users/cburr/mambaforge/conda-bld/dirac-grid_1712762382100/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/DIRAC/MonitoringSystem/Client/MonitoringReporter.py", line 26, in <module>
    from DIRAC.MonitoringSystem.Client.ServerUtils import getMonitoringDB
  File "/Users/cburr/mambaforge/conda-bld/dirac-grid_1712762382100/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/DIRAC/MonitoringSystem/Client/ServerUtils.py", line 7, in <module>
    from DIRAC.MonitoringSystem.DB.MonitoringDB import gMonitoringDB
  File "/Users/cburr/mambaforge/conda-bld/dirac-grid_1712762382100/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/DIRAC/MonitoringSystem/DB/MonitoringDB.py", line 35, in <module>
    from DIRAC.Core.Base.ElasticDB import ElasticDB
  File "/Users/cburr/mambaforge/conda-bld/dirac-grid_1712762382100/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/DIRAC/Core/Base/ElasticDB.py", line 4, in <module>
    from DIRAC.Core.Utilities.ElasticSearchDB import ElasticSearchDB
  File "/Users/cburr/mambaforge/conda-bld/dirac-grid_1712762382100/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/DIRAC/Core/Utilities/ElasticSearchDB.py", line 28, in <module>
    from elasticsearch import Elasticsearch
ModuleNotFoundError: No module named 'elasticsearch'
```

```bash
$ dirac-production-runjoblocal --help
Traceback (most recent call last):
  File "/Users/cburr/mambaforge/conda-bld/dirac-grid_1712762382100/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/DIRAC/Core/Utilities/ElasticSearchDB.py", line 16, in <module>
    from opensearchpy import OpenSearch as Elasticsearch
ModuleNotFoundError: No module named 'opensearchpy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cburr/mambaforge/conda-bld/dirac-grid_1712762382100/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/dirac-production-runjoblocal", line 6, in <module>
    from DIRAC.TransformationSystem.scripts.dirac_production_runjoblocal import main
  File "/Users/cburr/mambaforge/conda-bld/dirac-grid_1712762382100/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/DIRAC/TransformationSystem/scripts/dirac_production_runjoblocal.py", line 15, in <module>
    from DIRAC.Interfaces.API.Dirac import Dirac
  File "/Users/cburr/mambaforge/conda-bld/dirac-grid_1712762382100/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/DIRAC/Interfaces/API/Dirac.py", line 44, in <module>
    from DIRAC.DataManagementSystem.Client.DataManager import DataManager
  File "/Users/cburr/mambaforge/conda-bld/dirac-grid_1712762382100/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/DIRAC/DataManagementSystem/Client/DataManager.py", line 28, in <module>
    from DIRAC.MonitoringSystem.Client.DataOperationSender import DataOperationSender
  File "/Users/cburr/mambaforge/conda-bld/dirac-grid_1712762382100/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/DIRAC/MonitoringSystem/Client/DataOperationSender.py", line 16, in <module>
    from DIRAC.MonitoringSystem.Client.MonitoringReporter import MonitoringReporter
  File "/Users/cburr/mambaforge/conda-bld/dirac-grid_1712762382100/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/DIRAC/MonitoringSystem/Client/MonitoringReporter.py", line 26, in <module>
    from DIRAC.MonitoringSystem.Client.ServerUtils import getMonitoringDB
  File "/Users/cburr/mambaforge/conda-bld/dirac-grid_1712762382100/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/DIRAC/MonitoringSystem/Client/ServerUtils.py", line 7, in <module>
    from DIRAC.MonitoringSystem.DB.MonitoringDB import gMonitoringDB
  File "/Users/cburr/mambaforge/conda-bld/dirac-grid_1712762382100/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/DIRAC/MonitoringSystem/DB/MonitoringDB.py", line 35, in <module>
    from DIRAC.Core.Base.ElasticDB import ElasticDB
  File "/Users/cburr/mambaforge/conda-bld/dirac-grid_1712762382100/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/DIRAC/Core/Base/ElasticDB.py", line 4, in <module>
    from DIRAC.Core.Utilities.ElasticSearchDB import ElasticSearchDB
  File "/Users/cburr/mambaforge/conda-bld/dirac-grid_1712762382100/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/DIRAC/Core/Utilities/ElasticSearchDB.py", line 28, in <module>
    from elasticsearch import Elasticsearch
ModuleNotFoundError: No module named 'elasticsearch'
```

**Comment by chrisburr** [comment]
Actually this probably also means those scripts are subtly broken as they trigger the CS refresher thread before calling `parseCommandLine()`.
